### ISSUE TITLE
Incremental update of trust levels in a dynamic blockchain graph

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2805]
Within Tribler we aim to calculate and show trust level of our neighbors.

Trust levels evolve over time, as more information is coming in from our blockchain. Restarting the calculation from cratch every time new information comes in is prohibitively expensive.

We require an _incremental_ algorithm which can [update our sybil-resilient random walk algorithm](#1844). With our dataset from our deployed network it currently takes 6-9 seconds to do a full calculation. When we have a dataset locally of 50000 peers around us, we require an incremental algorithm. 

Key related work by [Stanford and Twitter engineers "Fast incremental and personalized PageRank"](http://dl.acm.org/citation.cfm?id=1929864):
```
For global PageRank, we assume that the social network
has n nodes, and m adversarially chosen edges arrive in a
random order. We show that with a reset probability of
!, the expected total work needed to maintain an accurate
estimate (using the Monte Carlo method) of the PageRank
of every node at all times is O( n ln m
!2 ). This is significantly
better than all known bounds for incremental PageRank.
For instance, if we naively recompute the PageRanks as
each edge arrives, the simple power iteration method needs
Ω( m2
ln(1/(1−!)) ) total time and the Monte Carlo method needs
O(mn/!) total time; both are prohibitively expensive. We
also show that we can handle deletions equally efficiently.
```

**Comment by devos50** [comment]
More relevant literature: http://repository.tudelft.nl/islandora/object/uuid%3A17adc7bd-5c82-4ad5-b1c8-a8b85b23db1f?collection=education

**Comment by Peiteng** [comment]
http://www-sop.inria.fr/members/Konstantin.Avratchenkov/pubs/mc.pdf
This paper introduces the Monte Carlo Methods in PageRank value

**Comment by Peiteng** [comment]
http://crad.ict.ac.cn/CN/abstract/abstract3238.shtml
This paper doesn't need to store the random path when updating the PageRank Value， compared with the paper: "Fast incremental and personalized PageRank"

**Comment by synctext** [comment]
Excellent work by Harvard University + Zurich: [Personalized Hitting Time for Informative Trust Mechanisms Despite Sybils](http://www.ifi.uzh.ch/ce/publications/Personalized_Hitting_Time_Liu_et_al_AAMAS_2016.pdf)  ( [thesis version](https://dash.harvard.edu/bitstream/handle/1/12705170/Brandon%20Liu%20-%20Senior%20Honors%20Thesis.pdf) )

**Comment by synctext** [comment]
2005 work: [
Incremental page rank computation on evolving graphs](http://dl.acm.org/citation.cfm?id=1062885)

**Comment by synctext** [comment]
First code: https://github.com/Peiteng/Incremental-Pagerank !

ToDo next meeting:
- generate 1 random graph
- change the network 5%, 10%, 25%, 50% etc.
- calculate your incremental pagerank
- how accurate is it? (re-calculate)
- _repeat above for numerous random graphs_

Key outcome plot : 
- X-axis percent change in graph
- Y-axes accuracy of incremental pagerank

**Comment by synctext** [comment]
Possible solo "blockchain Engineering" course. ToDo: take trustchain dataset, copy algorithms from state-of-the-art, possible enhance,  implement Python code, math beautiful equations on probability & stochastic.  @alexander-stannat  

[We establish a surprising connection between the personalized PageRank algorithm and the stochastic block model for random graphs, showing that personalized PageRank,](http://www.pnas.org/content/pnas/early/2016/12/19/1611275114.full.pdf) in fact, provides the optimal geometric discriminant function for separating the communities in stochastic block models over a wide class of functions. Building on this result, we develop stronger classifiers that, although scalable, are competitive with computationally much more demanding methods such as belief propagation.

**Comment by synctext** [comment]
First sprint:
- [ ] get dataset @jangerritharms 
- [ ] [understand the  initial code by Martijn of PageRank](https://github.com/Tribler/tribler/pull/3282/files#diff-387c813776d13167bd3a6118bbce82cb)
- [ ] build the most simple version of full PageRank
  - stand-alone code
  - simple text datafile reading
- Unit testing like example code by Martijn
- Then iterate and improve
  - measure [calculation time in Python 2.7](https://docs.python.org/2/library/timeit.html)
  - incremental
  - heuristic usage

**Comment by alexander-stannat** [comment]
First sprint finished.

I implemented a standard Monte Carlo random walk algorithm (R random walks starting from each node without resets, with average length reset_prob^-1). The page rank is determined by the number of visit times of each node divided by the sum over all visit times (see [algorithm 4](http://www-sop.inria.fr/members/Konstantin.Avratchenkov/pubs/mc.pdf))

For nodes that are added to the graph we run R random walks starting at the corresponding nodes.
For edges that are added to the graph we use the visit times of the node out of which the new edge goes and determine the number of random walks which should pass through the newly added edge. Then we run the given number of random walks starting at the node the new edge connects to and add the visit time of each node to the existing visit times vector.
For edges that are removed from the graph we do the same but subtract the visit times of each node from the visit times vector.

I tested the algorithm on a number of different example graphs, including the graph of the multichain data set and determined the execution times.

For the graphs generated by blocks 0-100 and 50-150, it took 24.5 seconds to compute the algorithm.
![incrpagerankfor100blocks](https://user-images.githubusercontent.com/37674654/43530173-37da91c0-95ad-11e8-81fa-1faf48b55196.png)
For the graphs generated by the blocks 0-1000 and blocks 500-1500 respectively, it took 72 seconds to compute the page ranks of both the new and the old graph.
Unfortunately, I couldn't run the algorithm on the entire data base, because Spyder froze.


The next step would now be to optimize the algorithm. [These guys](http://delivery.acm.org/10.1145/1070000/1062885/p1094-desikan.pdf?ip=145.94.227.165&id=1062885&acc=ACTIVE%20SERVICE&key=0C390721DC3021FF%2E512956D6C5F075DE%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&__acm__=1533133668_a3fce964e8cf7ad58b5ea00147083cbf) divide the graph into a partition Q containing all changed nodes/edges and no outgoing links, and a partition P. Seems like the right direction seeing as the multi chain network only grows in 'one direction' making such a partition easy to obtain.

I couldn't find an English version of the [Chinese paper](crad.ict.ac.cn/CN/abstract/abstract3238.shtml).  so I don't quite know what to do with it.

**Comment by vandenheuvel** [comment]
For inspiration: https://github.com/vandenheuvel/incremental-pagerank

**Comment by vandenheuvel** [comment]
Feedback in terms of coding:

- Write comments
- Use a unit testing framework
- Separate code into multiple modules, by function (e.g. move out the database code)
- Follow PEP8

Function wise changes:
**Compute only with totals**
Don't use the block graph directly, aggregate blocks for each public key. Either use contribution totals directly as edges, or scale them first (unclear how this should happen: capped at a limit, logarithmically, etc). Possibly, one could also use net contribution, and not have an edge at all if the net total is negative.

**All walks from a single node**
When using this algorithm in practice, there is only one node known to be secure: yourself. Take a random node and compute all values from the perspective of that node.

**Continuous updating**
A mechanism needs to be in place, which updates computed values once a new block arrives. Either using the saving of all walks and replacing them, or updating parts of walks as discussed, or use a vector of computed values.

**Think about churn**
Maybe, many public keys will never come online again. Maybe, these are best removed from the graph.

**Think about speed of convergence**
Matters a lot, especially if the computed value will determine its updated value after a new edge arrives.

**Comment by alexander-stannat** [comment]
I have written a [class](https://github.com/alexander-stannat/Incremental-Pagerank/blob/master/Page_Rank.py) to incrementally compute the personalized page ranks of a directed graph from the perspective of a predetermined node in the graph. Personalized page rank is an alternate version of page rank where the ranks of nodes are determined by their distance from a given seed node. In this class the page ranks are computed using the monte carlo method, whereby a number of random walks of predetermined lengths originate from the seed node and walk along the edges through the graph. They jump back to the seed node with a given probability at every step and the walk is terminated once it reaches a certain length. If a random walk reaches a "dangling node", i.e. a node with no outgoing edges it is reset as well. A vector of visit times is computed containing the number of times the random walk passes through the individual nodes and the page rank is given by the visit times divided by the accumulated visit times of all nodes in the graph. 

The personalized page rank given below is incremental, meaning that it can be recomputed every time the underlying graph structure is modified, i.e. edges and nodes are added or removed. In order to recompute the page ranks, one doesn't have to recompute the entire set of random walks through the graph. Instead, the given set of random walks is modified. The idea behind this is that a given random walk does not pass through every single edge. Only random walks that reach a node for which the outgoing edges have been modified, i.e. an edge is added or removed, or the weight of an edge is changed, need to be recomputed, starting from the first node for which such changes have occurred. I compare my results to the [regular power iteration method](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.link_analysis.pagerank_alg.pagerank.html) whereby i used 500 as a maximum number of iterations. The power iteration method is more accurate than the monte carlo mehtod. However, the goal was to implement an **incremental** pagerank. Seeing as recomputing the power iteration every time the graph changes, the monte carlo algorithm turns out to be the more efficient option. As the graph sizes increases will become more efficient than the power iteration. 

I created some [unit testing examples](https://github.com/alexander-stannat/Incremental-Pagerank/blob/master/Test_Cases.py) where graphs are randomly generated and the page ranks are computed (both monte carlo and power iteration) and then randomly modified, i.e. edges and nodes removed and added. Finally the page ranks are computed again. Once incrementally (monte carlo) and once by power iteration. I assert that both vectors of page rank values are approximately equal.
![Graph of randomly generated network](https://user-images.githubusercontent.com/37674654/44362794-6a5eab80-a4c2-11e8-8b3b-e99065915fb4.png)
I found out that the accuracy of the page rank vectors depends largely on the length of the random walks and not on the number of random walks generated. The graphs below show the euclidean distance between the two page rank vectors by length and number of random walks:
![convergence of random walk length seed 111](https://user-images.githubusercontent.com/37674654/44362949-f07af200-a4c2-11e8-8712-dc46fcc45fdb.png)
![convergence of number of random walks seed 111](https://user-images.githubusercontent.com/37674654/44362950-f2dd4c00-a4c2-11e8-944a-69248764e9e9.png)

We can see that the distance converges approximately to zero as the length of the walks increases and a walk length ca. 80 is very accurate. We also see that the number of random walks plays an unimportant role. 
Finally I have written a [class](https://github.com/alexander-stannat/Incremental-Pagerank/blob/master/Open_Database.py) that opens the database of trustchain transactions and generates a graph, where nodes correspond to public keys (peers) and the weights of edges correspond to the net data flow in between two peers. I ran the monte carlo algorithm on this data set and am now able to efficiently compute updates made to the trustchain database, incrementally. 

Finally Martijn gave me access to the new data set which I will incorporate into the algorithm.

**Comment by vandenheuvel** [comment]
**Make the implementation scale**
Available memory seems to be a bottleneck. Re-examine portions of your code on which a lot of time is spent; the goal is to handle the entire dataset. Use generators, delete statements and if necessary, move some of the preprocessing tasks to sqlite. 

**Normalized error value**
Make sure error values over different database sizes are comparable. I recommend using an average relative error (relative to the power iteration value).

**To cap or not to cap the walk length**
Two ways to do the walking:

1. Stopping and resetting walks probabilistically with a fixed probability
2. Stopping walks after a fixed number of steps and resetting probabilistically with a fixed probability 

We suspect the first one approximates typical personalized PageRank as implemented by NetworkX, while the second one results in slightly different values. The may explain the asymptotic behaviour of the error as measured in the above post: when the cap on the walk length increases, the second method approaches the first method. 

In the next sprint, also pick up the first method and compare.

**Sybil resistance**
Make artificial test cases for sybil resistance. Create one graph without a sybil region, and then compare with graphs which do have one. Vary in how connected the trusted node is to the region (as measured by shortest path, or average path lengths of the walks), as well as its size. Also, test whether extreme transaction sizes influence the rankings significantly. 

For completeness, include a quick comparison of the NetworkX PageRank and NetworkX personalized PageRank.

**Completing the picture**
Reflect on whether these results make sense when comparing with the relevant literature. Then, consider the following questions:

- Approximately, which database sizes is your algorithm (leaving aside practical io issues) able to handle? How long does processing take?
- Can you tell if the algorithm is sybil resistant? And is there an theoretical explanation for that?
- Which next steps should be taken, working towards closing this ticket?

**Comment by synctext** [comment]
As we [experimented with in the past](https://dl.acm.org/citation.cfm?id=2695868), there are multiple random walks:
- simple random walk
- weighted random walk
- [Metropolis-Hastings Random Walk](https://www.jstor.org/stable/2334940?seq=1#metadata_info_tab_contents)

**Comment by alexander-stannat** [comment]
**Sybil Resistance:**

I simulated a random graph of 500 nodes with a Sybil region of 50 nodes and a range of attack edges from 0 to 50. For each number of attack edges I compute the (ROC curve)[https://acutecaretesting.org/en/articles/roc-curves-what-are-they-and-how-are-they-used] and determined the area under the ROC curve as a measure of the sybil resistance of the algorithm. 

I also computed the proportion of false positives and false negatives for each number of attack edges and obtain the following results:

![area under roc curve](https://user-images.githubusercontent.com/37674654/45163276-5e782680-b1f0-11e8-84a9-863c61fa4ca3.png)
![proportion of false negatives](https://user-images.githubusercontent.com/37674654/45163278-5e782680-b1f0-11e8-9a3c-02ea745f3829.png)
![proportion of false ositives](https://user-images.githubusercontent.com/37674654/45163279-5f10bd00-b1f0-11e8-9a9e-76817b9435ae.png)

**Comment by synctext** [comment]
Please _no_ random walks of 100 hops! Sane values for reset probability = [15%, 30%]. Not 1%.
[See the empirical grounding and old paper of this](https://homes.cs.washington.edu/~arvind/papers/onehop.pdf)

**Comment by alexander-stannat** [comment]
![accuracy by number of random walks variables lengths](https://user-images.githubusercontent.com/37674654/45164458-c891cb00-b1f2-11e8-8ccf-79be8e58427d.png)
![accuracy by number of random walks fixed length](https://user-images.githubusercontent.com/37674654/45164459-c891cb00-b1f2-11e8-9235-c744d6e2aee6.png)

**Comment by synctext** [comment]
500 honest nodes, 1000 densely connected attackers, 0-500 attack edges which are randomly attached.
Reset probability = .5, .3, .2, .1 ?
ER model to connect honest nodes, 10k edges.

**Comment by synctext** [comment]
Reviewed [final project report](https://github.com/alexander-stannat/Incremental-Pagerank2/blob/master/Report.ipynb):
- URLs broken
- dropedge: http://www.eecs.harvard.edu/cs286r/courses/fall09/papers/tang09.pdf
- $M=\left<P,I,a,\omega\right>$
- $$ w((v_p,v<em>q)):=\sum\limits</em>{i\in{}I:a(i)=(p,q)}w(i,p) $$
- "this agent msut be completely"
- by $\tilde{E} is a matrix of only zeros, with a column of ones at the i-th place, with $i$ 
- Performance analysis
  - simple and easier to understood : probability of escape in Sybil region
  - ROC curves are a powerful and complicated measure

**Comment by vandenheuvel** [comment]
In our discussion on September 6, the following argument was made in favor of small hops:

> If you walk with a small reset probability and large average length, you extend your reach to the entire network, which we want to avoid. You'll always reach the sybils. "Six degrees of Kevin Bacon".

While it is true that it becomes possible to reach the entire network, but the probability of reaching one of the nodes which you can reach in _n_ steps but not in _n_ - 1 steps is extremely small. Indeed: the number of nodes reachable becomes enormous, but there is still only one walk. The probability that a far away node is visited many times, is extremely small, both because the walk isn't often very long and because there are so many nodes within reach. Instead, the walks will more often visit the nodes which are closer.

The above doesn't necessarily argue for long walks, but it shows that they can't be dismissed with that argument.

When we're approximating personalized pagerank, only the accuracy and computational cost matters. The incremental method using long walks when approximating personalized pagerank with low reset probability is accurate, see the above experiments by @alexander-stannat. Whether the computational costs are acceptable, still needs some discussion in my opinion (see bottom). If one is interested in nodes which are close by, I think it might be worth considering doing sparse matrix-vector multiplication to approximate.

1. First phase: A quick connectedness check with a maximum length, to limit the number of nodes for the second phase
2. Second phase: Build a sparse transition graph for the nodes found in phase one, and do a few sparse matrix-vector multiplications in numpy to find your probabilities

The result will be similar to personalized pagerank with high alpha. Example: Limit the nodes to third degree connections. Choose alpha = 0.5, and do three multiplications. Had we approximated with random walks, only 12.5% of walks would have reach out of our selection, when assuming equal probabilities for every hop. In practice, people will prefer helping those they know, so this number would be significantly smaller in practice (especially after implementing a peer selection algorithm which gives lowest priority to those with a connection degree that is too large).

As a bonus, the Tribler users could be given a simple choice they can understand: "do you only trust the friends of your friends, or also *their* friends?".

@devos50 could you weigh in on what, from a tribler design perspective, you think is an acceptable computational cost for such an algorithm? The current implementation would use a single core 100% for less than a minute for each update (updates can be accumulated and processed at once). @synctext mentioned that he prefers an algorithm which instead uses the cpu continuously but never longer than a few ms. @synctext what was the reason for this preference? Do you want to keep these computations on the twisted event loop?

**Comment by devos50** [comment]
This week, we brainstormed a bit about modularization of Tribler (splitting Tribler up in separate components, like IPv8, VoD, market etc). I think a dedicated 'trust module' would be an excellent first candidate to adhere to a modularized design. As a result, I would like to see this module being executed as a separate subprocess and communicate with the Tribler core using an IPC protocol (like JSON-RPC). Depending on the scheduler in the OS and the number of available cores, this subprocess should have minimal impact on the performance of the main Tribler process and overall user experience.

> @devos50 could you weigh in on what, from a Tribler design perspective, you think is an acceptable computational cost for such an algorithm?

If we follow the design I elaborated on in this comment, we have more flexibility regarding trust computations. Yet, it is very hard to come up with reasonable bounds for this. I would suggest playing around with the implementation and get more insight into the scalability and computational requirements of the algorithm first. To answer your question, we would need to know the tradeoff between required computation time and accuracy. I'm not sure whether the performed experiments are sufficient to answer this question yet.

Note that @ichorid can also help you with performance optimizations.

**Comment by vandenheuvel** [comment]
@devos50 while I understand that coming up with reasonable bounds is hard, I do think it is good to at least have a discussion about them. They're a requirement for the solution, and this requirements influences the search for a good algorithm. The one implemented by @alexander-stannat was rejected by @synctext because of its system load profile (alternating a short period of calculations and long periods of idle). This load profile is inherent to the algorithm, and as such the algorithm could have been rejected much sooner than it was. It is my opinion that @alexander-stannat needs, or at least would benefit greatly from knowing, such requirements up front while working towards a solution.

And lastly: isn't it too soon to spend time making performance optimizations? I would argue that other algorithms should be explored first, especially since the previous algorithm was deemed unsuitable.

**Comment by alexander-stannat** [comment]
> 
> 
> Reviewed [final project report](https://github.com/alexander-stannat/Incremental-Pagerank2/blob/master/Report.ipynb):
> 
>     * URLs broken
> 
>     * dropedge: http://www.eecs.harvard.edu/cs286r/courses/fall09/papers/tang09.pdf
> 
>     * $M=\left<P,I,a,\omega\right>$
> 
>     * $$ w((v_p,v_q)):=\sum\limits_{i\in{}I:a(i)=(p,q)}w(i,p) $$
> 
>     * "this agent msut be completely"
> 
>     * by $\tilde{E} is a matrix of only zeros, with a column of ones at the i-th place, with $i$
> 
>     * Performance analysis
>       
>       * simple and easier to understood : probability of escape in Sybil region
>       * ROC curves are a powerful and complicated measure

All code in the Report is now running bug free. The LaTeX compatibility issues have been fixed and all outgoing links are now actually outgoing :P 

Feel free to [check it out](https://github.com/Tribler/incremental-pagerank/blob/master/Report.ipynb) .

**Comment by alexander-stannat** [comment]
Next Steps:

Create a plugin to generate visualisations and calculations of trust in the network, using real-time tribler data. Make a user interface where users can see trustworthiness of their peers.
Talk to @mitchellolsthoorn about working together.

**Comment by synctext** [comment]
### Related work assuming _obedient users_.

Related work from the ancient times of file sharing and public goods. All ignoring real world security issues, like the Sybil attack. Thus showing the deadly gap between theory and Internet reality.
- [Incentives for Sharing in Peer-to-Peer Networks](http://robotics.stanford.edu/~kevinlb/welcom01.pdf); classical "Agent Utility" model, micropayments, and internal currency "points". ***2001*** Very early work.
- [Incentives for large peer-to-peer systems](https://ieeexplore.ieee.org/document/1626429)
![image](https://user-images.githubusercontent.com/325224/47140213-fe2fd680-d2bd-11e8-86b2-2b86592472c2.png)
- [Incentives to Promote Availability in Peer-to-Peer Anonymity Systems](http://csr.bu.edu/icnp2005/papers/10_dfigueiredo-anonymity1.pdf) 2005
- [Fairness, incentives and performance in peer-to-peer networks](http://svn.camrdale.org/school/papers/P2Pfairness.pdf) 2003
- [Free riding: A new challenge to peer-to-peer file sharing systems](https://ieeexplore.ieee.org/document/1174583) 2003
- [Service capacity of peer-to-peer networks](https://ieeexplore.ieee.org/document/1354647) 2004, very early model of Bittorrent tit-for-tat.
- [A simple reputation model for BitTorrent-like incentives](https://ieeexplore.ieee.org/abstract/document/5137450) 2009 work

Reality suffers from strategic manipulation, fraud, Sybil attacks, oversupply, and credit hoarding:
- "[Sybilproof Reputation Mechanisms](http://www.eecs.harvard.edu/cs286r/courses/fall08/files/paper-CheFri.pdf)", 2005 pioneering work
![reputation_formula_friendman_2005](https://user-images.githubusercontent.com/325224/47147169-eeb88980-d2cd-11e8-9bdc-c93fe39d0c40.png)
- [Overcoming free-riding behavior in peer-to-peer systems](https://dl.acm.org/citation.cfm?id=1120723), no answers, but asks the essential question: "How does the availability of cheap identities affect user behavior in P2P systems, and what are its implications on the desired generosity toward strangers?"  2005
- [The problem of upload competition in Peer-to-Peer systems with incentive mechanisms](http://dx.doi.org/10.1002/cpe.2856)  our own work from 2012

**Comment by synctext** [comment]
[Dynamic trust metrics for peer-to-peer systems](https://ieeexplore.ieee.org/abstract/document/1508367), early work, 2005
"One of the fundamental challenges for peer-to-peer (P2P) systems is the ability to manage risks involved in interacting and collaborating with priorly unknown and potentially malicious parties. Reputation-based trust management can mitigate this risk by deriving the trustworthiness of a certain peer from that peer's behavior history."

**Comment by synctext** [comment]
[Filtering trust opinions through reinforcement learning](https://www.ntu.edu.sg/home/boan/papers/dss14.pdf), AI-solves-everything, 2014 work
_solution: AI magic + make the problem simpler by assuming a witness can always be inserted into any transaction_
"we propose the Actor–Critic Trust (ACT) model, which is an adaptive trust evidence aggregation model based on the principles of reinforcement learning. The proposed method dynamically adjusts the selection of credible witnesses as well as the key parameters associated with the direct and indirect trust evidence sources based on the observed benefits received by the trusting entity.

**Comment by alexander-stannat** [comment]
Update:

Very basic GUI is now implemented. The idea was to implement an interactive graph visualising the Tribler network, including the trust rankings of all agents, determined by our current [Monte Carlo pagerank implementation](https://github.com/alexander-stannat/Incremental-Pagerank/blob/master/Page_Rank2.py).
The current implementation is still a skeleton of the final product and looks as follows:

<center>
<img width="402" alt="tribler network gui" src="https://user-images.githubusercontent.com/37674654/47650171-b0e61b80-db7f-11e8-9d39-b5f773e96a8a.PNG">
</center>

The code can be found [here](https://github.com/alexander-stannat/Incremental-Pagerank/blob/master/Trust_GUI.py). Ideally, it will resemble the current [Tribler network explorer](http://tribler.mualo.nl/) in design and layout. 

<img width="960" alt="tribler network explorer" src="https://user-images.githubusercontent.com/37674654/47650665-3c13e100-db81-11e8-945e-a8b2f2e5bcde.PNG">

So far, a few features are available, such as finding the highest ranking (most trustworthy) node in the network. This is the node that has the largest number of visit times out of all nodes in the network. However, it may not be the node everyone can or wants to interact with, due to the decline in transitive trust over multiple hops.

Another feature is the "Show Neighbourhood" button with which a node can get a close-up look of all it's adjacent nodes. The aim for the future is to create a GUI, in which the user can click on an arbitrary node in the network and then zoom into that node's respective neighbourhood. That way one could explore the entire Tribler network, along interaction paths.

Finally, we're working on a "Most Likely Path" feature which will highlight the path in the network along which the majority of random walks in the Monte Carlo algorithm have travelled. 

For our next steps, we will enhance the Interface's interactiveness, i.e. clicking on nodes and edges reveal information about them. More aesthetically pleasing design and layout and some additional features such as viewing the overall net contribution of nodes to the network, etc. This can be discussed in our next meeting.

**Comment by synctext** [comment]
Solid progress. Please focus on feature completeness and leave "GUI beauty" to others...

**Comment by alexander-stannat** [comment]
[Report](https://github.com/alexander-stannat/Incremental-Pagerank/blob/master/Report.pdf) in IEEE format now ready. Now It's back to the GUI.

**Comment by devos50** [comment]
Nice!

Side note, are you sure that's IEEE style? Looks a lot like the ACM template to me ;)

**Comment by alexander-stannat** [comment]
I have updated the [Trust GUI](https://github.com/alexander-stannat/Incremental-Pagerank/blob/master/Trust_GUI.py) to include a double-circle spring layout of the nodes in the network. See below
<img width="400" alt="tribler gui 3" src="https://user-images.githubusercontent.com/37674654/48710130-b3301880-ec07-11e8-9869-390d46636095.PNG">

A peer can view its immediate neighbourhood (2 hops) in this GUI and determine how trustworthy the nodes in its vicinity are. The nodes are ranked using our previous [Monte Carlo PageRank Algorithm](https://github.com/alexander-stannat/Incremental-Pagerank/blob/master/Page_Rank2.py) and are colourcoded based on their trustworthiness from red to green. 

Making the networkx plot of the graph interactive has proven to be challenging and it looks as though this will have to be hard coded, which is rather burdensome. For now, there seems to be no way around this. 

[Here](https://soniakopel.wordpress.com/2017/11/15/network-visualization-with-networkx-tutorial/) is an example of how that can be done. Note that this example shows how ineffective such hardcoding is.

**Comment by synctext** [comment]
Next sprint: connect to the live network; as of now 400+ MByte of Trustchain data, growing with 80k records daily. Keep track of _discovered Tribler users by you_: "discovered 7500 people".
![tribler_users](https://user-images.githubusercontent.com/325224/48711856-92b68d00-ec0c-11e8-94ad-6a534da76fba.png)

On making the bitmap image interactive
- ask @egbertbouman ; dumb @synctext method...:
- each click has an x1,y1 coordinate
- each node has an x2,y2 coordinate
- Magic find node with minimal ```calculateDistance(x1,y1,x2,y2)```

```import math  
def calculateDistance(x1,y1,x2,y2):  
     dist = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)  
     return dist  
print calculateDistance(x1, y1, x2, y2)  
```

Focus on real-time updates. Show _partly_ the fresh information that the random walk discovered. For instance,
![output](https://cloud.githubusercontent.com/assets/3630389/26485868/fc43112c-41f8-11e7-8a1f-fdb00a99778f.png)

**Comment by qstokkink** [comment]
Have a look at: 

 - https://github.com/Tribler/py-ipv8/tree/master/doc
 - https://github.com/Tribler/py-ipv8/blob/master/ipv8/attestation/trustchain/community.py

**Comment by alexander-stannat** [comment]
[Here](https://github.com/alexander-stannat/Incremental-Pagerank/blob/master/Report.pdf) is the current state of the report for the deep-dive meeting with the Ministry of Infrastructure tomorrow. 

At this point the algorithm is still a standalone implementation based on a static database. Starting February I will begin working on this full-time. The next steps from thereon out will be to:

- make incremental updates continuous by connecting to a real-time TrustChain crawler
- integrate the trust ranking into the Tribler GUI
- optimise in order to reduce run-time and error sizes

**Comment by vandenheuvel** [comment]
What exactly is plotted in Figure 13? I think you should invert your metric, because as it is plotted now it looks like your algorithm is performing consistently worse than random guessing.

**Comment by alexander-stannat** [comment]
@vandenheuvel The graph in figure 13 corresponds to the area under the [ROC curve](https://towardsdatascience.com/understanding-auc-roc-curve-68b2303cc9c5), a measure for determining the proportion of false negatives/positives of a ranking algorithm. You're right. Our current implementation of the PageRank approximation has a very high proportion of false positives/negatives. The reason for this are the very short random walks which we used in order to mitigate sybil attacks. This leads to nodes that haven't actually been discovered by any random walk being ranked as non-trustworthy (Sybil), because they have a PageRank of 0. This, of course shouldn't be the case, because nodes that haven't been discovered yet shouldn't be labelled Sybils. Instead, only nodes that are in the already discovered part of the graph **and** have very low trust values should be considered Sybils. Others should just be labelled "unknown". If we do that the accuracy of our ranking should improve dramatically. The graphs therefore need to be updated. Thanks for the feedback 😃

**Comment by synctext** [comment]
# Official start of master thesis

We have several online reading lists on trust. Start with writing a related work section. Focus on multiple domains, then sharpen to gossip of reputation info and Sybil attacks. The material already on this wiki:
- [ ] [Old ticket 31 with sociology, CS, Econ and math view](https://github.com/Tribler/tribler/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+mojonation#issuecomment-370789131)
- [ ] [Latency principle and seniority algorithm idea](https://github.com/Tribler/tribler/issues/2541#issuecomment-437691807) from the _universal mechanism to create trust_ tickets.
- [ ] [Latest model with local memory in a community](https://github.com/Tribler/tribler/issues/2541#issuecomment-445347871)
- [ ] Our own TUDelft work from 1999 by Prof. Jonker: [Formal Analysis of Models for the Dynamics of Trust based on Experiences](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.50.2334&rep=rep1&type=pdf)
![formal_analysis_of models for the dynamics of trust based on experiences--formula](https://user-images.githubusercontent.com/325224/52199968-c8602f00-2867-11e9-93ec-78d7ec73b586.png)
- [ ] [Above here in this ticket](https://github.com/Tribler/tribler/issues/2805#issuecomment-430952541) is a list of related work. With formula pictures from NetLogo and P2P file sharing [Incentives for large peer-to-peer systems](https://ieeexplore.ieee.org/document/1626429)
![image](https://user-images.githubusercontent.com/325224/47140213-fe2fd680-d2bd-11e8-86b2-2b86592472c2.png)
- [ ] [model assumptions](https://github.com/Tribler/tribler/issues/3357#issuecomment-374562088) for trust (such as life-long identities and refusal to disseminate)
- [ ] Great pictures from @jangerritharms  Commercial reputation systems:
![image](https://user-images.githubusercontent.com/7403807/35967644-c4ccefda-0cc1-11e8-80c5-1661ebeeac4c.png)
- [ ] Research reputation systems:
![image](https://user-images.githubusercontent.com/7403807/35967685-ea9401b8-0cc1-11e8-8eca-db479cd46d66.png)
Taken from: [Reputation systems: A survey and taxonomy](https://ac.els-cdn.com/S0743731514001464/1-s2.0-S0743731514001464-main.pdf?_tid=adf9cc4a-0cb9-11e8-8980-00000aab0f01&acdnat=1518085406_54d193affe86f2574c66e96eb21a3456)

**Comment by synctext** [comment]
Meetings minute: continue intense reading and wrap-up "blockchain engineering" course work.

**Comment by cuileri** [comment]
Detected a problem with both Alexander's and my implementation of random walks:

![rw_ex](https://user-images.githubusercontent.com/22027137/54031019-cf9f9300-41ad-11e9-8491-3390061d9e90.png)

In 1000 random walks initiated by root **r**
- **c** will be visited 990 times (or 990 x (1-p) times, where p is the reset probability)
- **b** will be visited 10 times

even though they did the same amount of job.

**Winning strategy (Possible attack):**
Perform work for the one who performed much work but have not received any work yet.

**Solution:**

![formula](https://user-images.githubusercontent.com/22027137/54033087-ada90f00-41b3-11e9-8cae-f0fd547435aa.png)

**Comment by synctext** [comment]
> Detected a problem 

I would call this a feature: trustworthiness of information is taken into account. In this extreme numerical example it has a nice dramatic effect (10 vs. 990). These are synthetic numbers, the effectiveness of a Sybil attack prevention method should be done with the really-hard-to-get attack datasets.

**Comment by vandenheuvel** [comment]
I could consider the node 'b' in the example to be more trustworthy that 'c': they have made the same contribution to this part of the graph, however, from the perspective of node 'r', 'b' is closer.

**Comment by synctext** [comment]
Large body of related work from the AI agents-community. From 2002 with currently 1607 citations, "[the Beta reputation system](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.480.4572&rep=rep1&type=pdf)". Their magic:

![image](https://user-images.githubusercontent.com/325224/56355661-2b126700-61d7-11e9-9dc6-3ec37555e3ae.png)

**Comment by synctext** [comment]
[Latest 2019 TRUST workshop papers](https://sites.google.com/view/trust2019/program)
```
The AAMAS 2019 TRUST workshop will have the theme: The Whole World is Watching. The 
development of multiagent trust and reputation systems has been a vibrant topic of research at AAMAS 
conferences each year. This year, the workshop will aim to introduce our field of study to researchers in 
related subfields and to industrial representatives who may be attending the conference in order to learn 
more about AI. There has been increasing interest worldwide in the use of AI within private and public 
sector organizations, and a common concern has been the trustworthiness of the systems being used.
```

**Comment by synctext** [comment]
2018 "Network Reciprocity" paper, great overview of the big picture, https://doi.org/10.1073/pnas.1707505115

"Experiments show that network reciprocity promotes cooperation under a restrictive condition: The benefit of cooperation must outweigh the total cost of cooperating with all neighbors (39). Our question, therefore, is whether this condition can be relaxed by combining two cooperation-promoting mechanisms. Specifically, are there any synergies to be gained by aiding network reciprocity with costly punishment?"
"In total, 225 participants were recruited to play 50 rounds of the game."
Nice work, that last bit also shows how artificial such lab results are.

**Comment by synctext** [comment]
Thesis work moved to the "proximity" Sybil attack mitigation ticket #4481

**Comment by synctext** [comment]
This issue needs to be promoted and renamed. Contains a wealth of info. How are we going to re-organise all these tickets of past 7+ years?
