### ISSUE TITLE
Perfect Darknet Roadmap Ticket

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3]
- [ ] _long-term tit-for-tat for anonymity_

  InternetOpen community to disseminate sharing ratio of participants. You need to help and relay traffic of others. Related experimental work in the Tor community: [GoldStar, PAR, BRAIDS, LIRA, TEARS, and TorCoin](https://blog.torproject.org/blog/tor-incentives-research-roundup-goldstar-par-braids-lira-tears-and-torcoin) (Tribler Tickets: partly #1230, also #5)
- [ ] _Tribler users **never** become an exit node._ 

  We need to protect our users from lawyer-based attacks. The Internet should have privacy by default. End-to-end encryption is the default and no exceptions. Only offer downloading from hidden seeds in upcoming versions. Additionally, no unprotected uploading/seeding, only through hidden service. We need a require connectability flag: #1174. Faulty approach: #885,     @rjruigrok 

- [ ] _Collective intelligence around reliability of anonymous relay partners_

  Share with the rest of the network who is actively helping others and who is freeriding. Introduce a Bitcoin-like accounting system. Instead of pointless hashing we use proxy helping bandwidth as our proof-of-work. Our protocol follows the Tor specification as much as possible, our circuits have a maximum lifetime of 10 minutes and also terminate after 55MByte of traffic (security limiters). Similar to private Bittorrent communities we use the sharing ratio to identify freeriders. Double signed signature record is created after proxy helping. These proof-of-work records are shared in the community (like Bitcoin public ledger). Each peer builds a database with the reliability of their neighbors, visualize in a graph (locally; no central accountant, controlling server).  #5

- [ ] _real-time statistics of you contributions and tunnel ratio

Notify users they are freeriding and disable anonymous downloading. <be harsh, Tribler is only for social people>.

- [ ] _real-time anonymous tunnels reliability statistics_

Each member of the collective measures their perception of network performance and shows it to the user. Advanced programmer-minded feature and debugging. Add to the Tribler debug screen how many unique neighbors have been seen. Measure the proxy bandwidth donations and online duration (reliability) of yourself and neighbors. Show broken tunnel events. Show overall tunnel + hidden seeding reliability and performance for a tunnel tests and 50MB downloads.

**Comment by colin1497** [comment]
With regard to "never" being an exit node, a more logical/usable approach is to allow being an exit node only for your own torrents.  While ideally the darknet just works, a reasonable method of usage is: download torrent non-anonymously and switch to anonymous and only seed to the darknet after completion.  Upon starting a torrent download, this process should be automatically selectable as an option, as in:

1) Download anonymous
2) Download public
3) Download public, switch to anonymous for seeding

Ideally there would be some feedback provided about the health of the torrent within the darknet, so if you were unlikely to have darknet success with option 1), you could easily select option 3).

**Comment by vvs-** [comment]
This paper has interesting relations to your work: [Kadupul: Livin' on the Edge with Virtual Currencies and Time-Locked Puzzles](http://anil.recoil.org/papers/2015-diynet-kadupul.pdf)

**Comment by synctext** [comment]
__copied the text from our old ISSUE 1 ticket for archiving purposes, dated 5 March 2013__
- [ ] _Tribler anonymous downloads are fast_
  Only 330KByte/sec is unacceptable for our video streaming use-case. Currently our GCM cypto or other bottleneck is slowing things down.  #1882  #2548 
- [ ] _User experience similar to Youtube_
  Toward a Youtube-like experience within Tribler. Use the thumbnails pre-view of videos as the key navigation and content selection tool. Integrate our recommendation engine to the GUI, like Youtube. #1846. @devos50 
- [ ] _Anonymous Video streaming, similar experience to Youtube on-demand service_
  Fast and robust downloads from hidden seeds. Users may need to wait a minute, but it simply works. Anon swarming: #1885  @lfdversluis 
- [X] _Tribler users **never** seed naked in Bittorrent swarms._ 
  Bittorrent swarms offer no protection, they leave people exposed and naked. Hidden seeding is the default in Tribler for sharing content and can only be disabled deep in the settings screen. This ensures sufficient content becomes available with strong privacy in our darknet. Hidden seeding requires connectability of rendezvous and introduction points.
- [X] _Tribler can download from both hidden seeders and existing Bittorrent swarms._ 
  Tribler offers the best of both worlds. It downloads from hidden seeders using end-to-end encryption and through exit nodes from normal Bittorrent seeders. Tribler offers these downloads in parallel and tries to get the best download speed from both of them. The fallback option is outdated, #885.
- [x] _Tribler users **never** become an exit node, unless they explicitly volunteer._ 
  Our smooth backwards compatibility with Bittorrent comes with the cost of exposure in existing Bittorrent swarms. We need volunteers to run "exit nodes". These are the peers that receive encrypted messages from the darknet and unencrypted messages from Bittorrent peers. Running an exit node has proven to be a risky non-trivial task for the main Tor community. Lawyer-based attacks are very real for exit node volunteers. Ideally, only a single copy of each piece of content needs to be relayed by our exit nodes. If content is "pulled into the darknet" we can switch to end-to-end encryption and rely on hidden seeding. Ticket: #1174
- [ ] _Sharing ratio enforcement using Multichain credits_
  Build in mechanism to determine who is helping others and who is freeriding. Improve our Bitcoin-like accounting system, called multichain. Similar to private Bittorrent communities we use the sharing ratio to identify freeriders. Double signed signature record is created after proxy helping or hidden seeding. These proof-of-work records are shared in the community (like Bitcoin public ledger). Each peer builds a database with the reliability of their neighbors, visualize in a graph (locally; no central accountant, controlling server).  #5  #1843, Sybil attack: #1844 pretty pictures: #1781 multichain brainstorm: #31 @pimotte @pimveldhuisen @Captain-Coder 
- [ ] _credit mining for anonymous seeding_
  Donate 25-100GByte to Tribler. Possibly even 1TByte. Automatically boost poorly seeded anonymous swarms. Maximize the yield of your bandwidth by automatically detecting and anonymous seeding of swarms. #573 #655 #21, running code: #23 #1842 @ardhipoetra 1TByte: @Pathemeous 
- [ ] _Android support for video recording and upload into Tribler/Bittorrent_
  An Android app with the capability to record videos and upload the straight into Tribler as a Bittorrent swarm. Your mobile phone becomes a TV station, broadcasting videos in its own Tribler Channel. Tribler users can subscribe to your videos and see what is new. Support thumbnails. #1782 https://github.com/kivy/python-for-android/pull/405 @brussee

**Comment by Destroyinator69420** [comment]
Spam resistance could be implemented by using hashcash. It would work because if the average computer took about 1 minute to crack a sha3-512 hash, then it would be unfeasible to send mass amounts of spam.
