### ISSUE TITLE
Uncovering the fundamental laws of trust using crowdsourcing

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4475]
_Devise an ecosystem in which rules that govern trust emerge from the wisdom of crowds._

This is a multi-year issue to evolve laws of trust, prove their merit and calibrate psychologically-grounded models of trust. We assume the fundamental laws of trust can be expressed as executable code combined with data about observations, actions, and beliefs of others. Central elements are the trust function. _speculative issue; REQUIREMENT: we already have achieved a less hard goal of end-to-end reinforcement learning and self-replicating agents: #3752.
- [ ] develop an ecosystem in which a trust function can be edited by all (part of IPv8 plugins, https://github.com/Tribler/tribler/issues/2943#issuecomment-476568507)
- [ ] Everything is expressed as a parameter and suitable for mutation: all information storage (enabling indirect reciprocity), database technology (e.g. trustchain tamper-proofness), and strategies (tit-for-tat,win-stay,lose-shift, etc.)
- [ ] everybody can discover, select, mutate, and gossip any trust function
- [ ] all users obtain a certain satisfaction or utility within our ecosystem (simplistic metric: days of usage)
- [ ] all users gossip about their used trust function and obtained utility
- [ ] trustworthiness of gossip is calculated, creating a circular dependency and evolutionary process
- [ ] periodically each user evaluates the trust function they use and perceived utility
- [ ] Craft a positive reinforcement feedback loop which selects a semi-random new trust function with a bias towards superior utility
- [ ] Attract scientists by making all data easily available for machine learning research
- [ ] Simulate emergent effect of scientists publishing on trust function improvements and experimental validation (e.g. trust engineering)
- [ ] Ecosystem drifts towards an understanding of the fundamentals of trust

**Comment by ichorid** [comment]
> * all users gossip about their used trust function and obtained utility
> * trustworthiness of gossip is calculated, creating a circular dependency and evolutionary process

I predict that the first function that will get "the selfish gene" thing done right will take the network by storm :wink:
