### ISSUE TITLE
deployment monitoring and epic progress dashboard

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4999]
To better organise ourselves we need more critical information in 1 place.

The coming time we aim to close #1 finally. Our progress towards this goal and how stable we are should be captured in a Tribler-at-a-Glance dashboard. Example from Jenkins:

![image](https://user-images.githubusercontent.com/325224/70456551-971b4580-1aae-11ea-8eaf-e00b170ed89a.png) https://medium.com/kj187/jenkins-job-dashing-widget-cc72feeed654

![image](https://user-images.githubusercontent.com/325224/70456714-f5482880-1aae-11ea-9d10-5602e1e96bb6.png) https://www.level-up.one/6-of-my-favorite-jenkins-plugins/

![image](https://user-images.githubusercontent.com/325224/70456737-06913500-1aaf-11ea-927d-3904fdeab1b6.png) https://www.datadoghq.com/blog/monitor-jenkins-datadog/

Tribler critical information candidates:
- stability issues
  - crash reports from the wild (24h, last week, last month) latest devel, latest stable version and all versions
  - Application tester with random clicker number of faults (24h, last week, last month) latest devel, latest stable version
  - burn-in testing of running Tribler for 1 week: total CPU cycle, peak memory, total disk IO (crash or run-away resource usage)
  - issues pending
- performance monitoring
  1. Anonymous end-to-end download performance (latest devel, latest stable version)
  2. Exit node based download speed
  3. Start of download delay, (non-)anonymous mode
  4. First time startup time
- deployment monitoring
  - explorer Trustchain, growth of blocks in (last minute ! ; last hour ; last day; last week ; all time)
  - exit node status (CPU, connections, idle slots, memory?)
  - traffic stats
  - metadata status: keyword searches, channel gossip community

**Comment by devos50** [comment]
Interesting visualisations! Somewhat related to https://github.com/Tribler/tribler/issues/3508 (at least the TrustChain deployment monitoring).

e2e anonymous download is an excellent candidate for performance monitoring and should not take long to setup. I think @ichorid addressed this a while ago actually but it has not been actively monitored since then. In fact, making us (more) aware of failing tests/validation experiments is becoming a necessity as the number of different tests that run with fixed time intervals is growing.

I think we have to address this issue rather sooner than later. The problem is that if we do not do it, we will have a proliferation of different tools. Currently, we have the TrustChain explorer, Tribler user statistics, the error reporter and all tests/monitors on Jenkins. There might be some opportunity to merge some tools, which eases maintenance. 

> metadata status: keyword searches, channel gossip community

This might be a dangerous one to monitor and could be a violation of ones privacy expectations of Tribler.

**Comment by synctext** [comment]
Please look at [FileCoin slipped roadmap](https://filecoin.io/blog/roadmap-update-february-2020/). After Release 7.5 I'm considering that we work together on the first _Jenkins dashboard_ for 2 weeks:
- [ ] arrange hardware monitors with obscene awesomeness, due to size (@synctext) <IMG src="https://user-images.githubusercontent.com/325224/78009418-496a6780-7341-11ea-99ed-c58d9663a7e3.png" width=170>
- [ ] Anonymous end-to-end download performance (latest devel, latest stable version) (@egbertbouman)
- [ ] crash reports from the wild (24h, last week, last month) latest devel, latest stable version and all versions (@ichorid)
- [ ] Application tester with random clicker number of faults (24h, last week, last month) latest devel, latest stable version (@devos50)
- [ ] IPv8 traffic stats with total of unique number of public keys in last (24h, last week, last month) within discovery community (heard about only, responsive) (@qstokkink)
- [ ] explorer Trustchain, growth of blocks in (last minute ! ; last hour ; last day; last week ; all time) (@grimadas)
![image](https://user-images.githubusercontent.com/325224/78007955-4a01fe80-733f-11ea-8882-7ca8d26a9306.png)

**Comment by qstokkink** [comment]
Can we decide on some software/library to use (or to make) to graph all of this data? All sorts of dashboard creation tools exist.

**Comment by devos50** [comment]
Most of this data can either be extracted from our existing Jenkins Job using the API, or from our running Trustchain explorer backend, also with API requests. One of the question we should also answer, is whether we want a dedicated website for this. Jenkins unfortunately does not provide the tools for such real-time data, and integration of this dashboard in Jenkins would just be a new job with succeed/fail status.

> arrange hardware monitors with obscene awesomeness, due to size

We should secure a prominent spot at the coffee machine ☕️

**Comment by qstokkink** [comment]
I propose starting with something "easy". Exposing GitHub events through `tribler.org`:

 - Add a webhook to GitHub for the Tribler repository (sending POST requests to the `tribler.org` domain).
 - Add a new page (`tribler.org/githubevents`?) which renders all GitHub events (possibly with websockets for live updates).

The idea is that we can reuse the resulting backend for another (bigger and better) dashboard and we'll have something to look at in the mean time.

**Comment by devos50** [comment]
One way to get more insights into our user count is by analysing the crawled TrustChain data. The plot below is generated based on our current dataset, with over 80.000 users and 123 million records. The (major) releases of Tribler are annotated.

![identities_per_day](https://user-images.githubusercontent.com/1707075/87545501-5a4ca800-c6a8-11ea-9254-dca4e70302f5.png)

Parsing this 97GB database, however, is computationally intensive and could be done on a daily basis for example. A dashboard could include this static image.

**Comment by synctext** [comment]
In 2006-2009 we had initial deployment monitoring. Included in Zeilemaker master thesis.
![image](https://user-images.githubusercontent.com/325224/87681982-97d03480-c77f-11ea-9d07-d9b293e88440.png)

**Comment by xoriole** [comment]
Based on data we already have
![Screenshot from 2020-09-04 10-27-45](https://user-images.githubusercontent.com/1442867/92218585-a098d900-ee99-11ea-93b4-670c212c0ef9.png)

**Comment by synctext** [comment]
InfluxDB:  34,082 commits, 19.5k of stars on Github

**Comment by xoriole** [comment]
InfluxDB and Graphana are indeed good choices. 
> 1.Custom client-side code to prepare anonymized statistics
2.Dedicated server with custom API as an entry point
3.InfluxDB for storing anonymized data
4.Grafana for displaying beautiful graphs

I have done some work on 1 and 2. I'm extending https://release.tribler.org/docs to receive anonymized data from the client.  That can be the entry point to further processing using InfluxDB and visualizing on Graphana.

**Comment by kozlovsky** [comment]
We probably can use InfluxDB Jenkins plugin to put deployment statistics into the InfluxDB:
https://wiki.jenkins.io/display/JENKINS//InfluxDB+Plugin

**Comment by synctext** [comment]
Change of plans:-)
By 25 September aim to have plots in Jenkins. The PopularityCommunity is crawled and health statistics are refreshed every few minutes or half an hour. After this test project we determine what we need and roadmap.

**Comment by devos50** [comment]
> exclusively rely on unit tests

I think a key metric is the stability of our unit tests. Currently, unstable unit tests (both on `devel` and our release branches) are delaying the development process. Converting the test suite to pytest, which should make the debugging process of errors in the tests easier, is much more work than I anticipated.

My suggestion would be to continuously run all unit tests on a dedicated machine and include in the upcoming dashboard how stable they are (e.g., % of runs failing during the last day).

**Comment by synctext** [comment]
Related work: https://stats.goerli.net/
![image](https://user-images.githubusercontent.com/325224/96460905-065fdb00-1224-11eb-8d1c-43d4ef79d7c6.png)

**Comment by synctext** [comment]
Impressive progress! Our .yml and servers are getting in much better shape. We can even see in real time the upgrade speed. Learned something new: they upgrade quite fast. Previous years we never had this.
![Screenshot from 2021-01-12 11-14-10](https://user-images.githubusercontent.com/325224/104445394-59ce9480-5599-11eb-9aa4-24988ccead05.png)

**Comment by synctext** [comment]
Yeah! More pretty graphs, exit node peak: 121 GiB per second
![image](https://user-images.githubusercontent.com/325224/110642906-ca69ea00-81b3-11eb-9897-395d18584eea.png)

**Comment by one-two-my-gad** [comment]
cool

**Comment by synctext** [comment]
Example: https://data.syncthing.net/
File sync with central servers discovery and no spam measures. Great deployment monitoring!

**Comment by synctext** [comment]
@kozlovsky Could you please duplicate this specific https://data.syncthing.net/ graphs and wrap up the Grafana work?
This is quite a useful and simple graph to have.
```Users Joining and Leaving per Day === This is the total number of unique users joining and leaving per day. A user is counted as "joined" on first the day their unique ID is seen, and as "left" on the last day the unique ID was seen before a two weeks or longer absence. "Bounced" refers to users who joined and left on the same day.```

**Comment by synctext** [comment]
> To better organise ourselves we need more critical information in 1 place.

The mission was to put everything in one place. The big danger is to partially put everything together, but actually create the n+1 place called Grafana where data is fragmented. Full user experience pipeline:

1. Keyword search performance for Tribler (locked somewhat into Google)
1. Website visits to Tribler.org (Github hosting statistics export)
1. Crawling of our .exe download stats from https://githubdownloads.com/?username=tribler&repository=tribler  ```Tribler-7.10.0.dmg (60.20 MiB) - downloaded 3,241 times. Last updated on 2021-07-14```
1. How many unique users are our network health crawlers talking to?
1. How many unique users are using our exit nodes?
1. How many unique users are using our various initial bootstrap nodes?

A single page having graphs for the health of each step in our user journey would help to identify faults. Like: 
![image](https://user-images.githubusercontent.com/325224/136019968-41d4b9e9-0563-46e5-b573-ba88f613ece2.png)

**Comment by synctext** [comment]
When we have hired more developers we can re-visit this issue. We need to focus on putting everything inside application-tester and existing code. [Example of IPFS people](https://github.com/dennis-tra/nebula-crawler) on DHT health.
<IMG src=https://raw.githubusercontent.com/dennis-tra/nebula-crawler/main/docs/grafana-screenshot.png width=900>

**Comment by synctext** [comment]
[IPFS people](http://162.55.187.75:3000/d/CSQsORs7k/nebula?orgId=1) have nice uptime monitoring script (DHT only level):
![image](https://user-images.githubusercontent.com/325224/196888963-bb40ff94-7f89-4320-862b-ddc5c82aa9c2.png)

**Comment by synctext** [comment]
We take screenshots, [takes a few clicks to find (application tester)](https://jenkins.tribler.org/job/Deployment-Tests/job/Run_Tribler_Release/job/Run_Win7_64bit/ws/screenshots/screenshot_1663672067.jpg)
![image](https://user-images.githubusercontent.com/325224/198240042-8fd3c8e4-b14e-4df7-b969-f757664ba46f.png)
Plus smooth Github actions: https://github.com/Tribler/tribler/actions/runs/3330189428/jobs/5508351618
![Screenshot from 2022-10-27 10-57-49](https://user-images.githubusercontent.com/325224/198240389-5a7d0668-4a6b-4ed2-881e-ae214ad826db.png)

**Comment by drew2a** [comment]
This is yet another indication that choosing Grafana+Prometheus may not have been the best decision for our "new" dashboard. We already have ample sources of information, so adding another unique source doesn't seem optimal. What we really need is a singular place to integrate all existing information.

From my perspective, here's what we should do (with a rough time estimation):

1. Select a tool capable of integrating data from all existing information sources (1w).
2. Install the tool (1d).
3. Ensure the selected tool can analyze the entirety of this information and present it using a simple traffic-light-style indicator: 🟢 🟡 🔴 (3d).
4. Consolidate all these sources into a single dashboard (1m-2m).
5. Make this tool easily accessible for all developers:
   1. Provide easy access to a web page (1d).
   2. Dispatch daily summary notifications (1d).
   3. Send out alerts concerning critical incidents (1d).


Our information sources:
1. Jenkins (Experiments, Application Tester, Release Builds)
2. Download statistics:  https://release.tribler.org/dashboard/ 
3. Grafana: https://dashboard.tribler.org
4. Infrastructure monitoring tools
5. Sentry
6. Metabase (crawlers)

(did I miss something?)

**Comment by kozlovsky** [comment]
I think that of all the services we use for dashboards and monitoring (Prometheus, InfluxDB, Grafana), Prometheus is the most reliable (and can display monitoring graphs without Grafana), while the most problematic was InfluxDB; most dashboard outages were caused by it.

It may be worth spending time to set up Prometheus alerts, as it should cover most of the current problems.

For persistent time series data, the most convenient data storage may be [TimescaleDB, which can replace InfluxDB and fix most problems](https://www.timescale.com/blog/timescaledb-vs-influxdb-for-time-series-data-timescale-influx-sql-nosql-36489299877/).

But trying something simpler like [Graphite](https://logz.io/blog/prometheus-vs-graphite/) is also possible.

**Comment by xoriole** [comment]
Since Grafana is currently used for deployment monitoring and as far as I understand there is no immediate priority to work on an alternative, I'm unassigning myself from this ticket.

**Comment by qstokkink** [comment]
Indeed, we have a solution in place. This issue is - at the very least for now - resolved. **_If_** we have specific alternatives that we want to explore in the future, another issue can be opened.
