### ISSUE TITLE
7.5 experimental release checklist

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5149]
- [x] Merge 7.4.x fixes
- [x] Implement upgrader for Pony DB 7(6)->8: create necessary indexes
- [x] Implement a basic remote query community to facilitate fast Channels bootstrap
- [x] ~~Make sure TorrentChecker works as intended (uses correct tracker URLs)~~
- [x] GUI: check torrents on click, not just on selection change
- [x] VersionManager must use `X.Y` subdirectory format.
- [ ] Fix the problem with repeated notifications on already downloaded torrents on startup
- [ ] :boom: Recheck thrice that upgrading works from 7.2.x, 7.3.x, 7.4.x, 7.5.x versions :boom:

**Comment by ichorid** [comment]
Well, the experimental version is out.
