### ISSUE TITLE
Start a new conference series?

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#5182]
We believe the tragedy of the commons problem can be solved. Coming decades we believe the first solution in an online context is likely, given the pace of innovation in game theory, mechanism design, governance models, blockchains, reputation systems, and decentralised autonomous organisations.

We would like to build a focussed community of scientists who build the theory and experimental experience in this area: engineering the commons.

Options to explore:
- [ ] is this the correct focus and direction
- [ ] IEEE or ACM accreditation
- [ ] start first years as a side workshop at big conference or mini pre-conference
- [ ] select key scientist to approach
  - At Delft
  - In Netherlands/Europe/Global
- [ ] create list of conferences to potentially target

**Comment by rellermeyer** [comment]
You could consider running a workshop at Middleware '20 in Delft. Submission deadline for workshops will most likely be in May.

**Comment by synctext** [comment]
We need 2-3 research groups at a well known universities to partner with. Let's aim for Middleware. Long list of like minded scientists in numerous fields:
- [Will Democracy Survive Big Data and Artificial Intelligence?](https://www.scientificamerican.com/article/will-democracy-survive-big-data-and-artificial-intelligence/),  _Dirk Helbing_, Bruno S. Frey, Gerd Gigerenzer, Ernst Hafen, Michael Hagner, Yvonne Hofstetter, _Jeroen van den Hoven_, Roberto V. Zicari, Andrej Zwitter
- [The Need for an Innovation Principle in Regulatory Impact Assessment: The Case of Finance and Innovation in Europe](https://onlinelibrary.wiley.com/doi/pdf/10.1002/1944-2866.POI374), Pēteris Zilgalvis (European Commission/Oxford)
- "[Can an economy survive without corporations? Technology and robust organizational alternatives](https://pdfs.semanticscholar.org/45ae/21b3ce254352b8abb2dd1c5790bd79c80a66.pdf), The University of Michigan, Prof. Gerald F. Davis
- "Competition among Liquidity Providers with Access to High-Frequency Technology", Dion Bongaerts (Erasmus University)
- [Talk is silver, code is gold? Beyond “object-centric” notions of contribution in peer production](https://papers.ssrn.com/sol3/Delivery.cfm/SSRN_ID3272342_code3172781.pdf?abstractid=3272342&mirid=1), David Rozas, _Nigel Gilbert_, Paul Hodkinson, Samer Hassan
- [Amplifying the Collective Intelligence of Teams with Swarm AI](https://ci.acm.org/2019/assets/proceedings/CI_2019_paper_37.pdf), DAVID ASKAY AND LYNN METCALF et. al.
- [Selfishness Drives Collective Cooperation and Network Formation](https://ci.acm.org/2019/assets/proceedings/CI_2019_paper_54.pdf), Korosh Mahmoodi and Cleotilde Gonzalez (CMU)
- _ongoing_

https://www.google.com/search?q=collective+cooperation

**Comment by devos50** [comment]
If we're aiming for Middleware, let's have a look at the workshops last year: https://2019.middleware-conference.org/workshop_accepted.html.

**Comment by synctext** [comment]
Done 1! Great success: [1st International Workshop on Distributed Infrastructure for Common Good](https://dicg2020.github.io/) .
Now we need to survive and even thrive for the 2nd edition of this workshop.

**Comment by synctext** [comment]
Nearly doing 2! https://dicg-workshop.github.io/2021/ Closing issue.
