### ISSUE TITLE
7.5.0-rc2 todo checklist

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5232]
Outstanding issues to be addressed before releasing 7.5.0-rc2:

- [x] [Future-related crash](https://github.com/Tribler/tribler/issues/5220)
- [x] [Embedded null character](https://github.com/Tribler/py-ipv8/issues/714)
- [x] [Unload pex bug](https://github.com/Tribler/tribler/issues/5226)
- [x] [Catching more `gaierror`s](https://github.com/Tribler/tribler/issues/5167)
- [x] ~~[Windows and Mac deployment problem](https://github.com/Tribler/tribler/issues/5229)~~
- [x] [No relaying // no credit](https://github.com/Tribler/tribler/issues/5231)
- [x] [Resolving tracker :task already exists](https://github.com/Tribler/tribler/issues/5241)

Fixes for these should contain minimal changes and be merged into `release-7.5` branch.

**Comment by ichorid** [comment]
Releasing RC2, so closing this.
