### ISSUE TITLE
Channels 3.0 architecture and roadmap: HTML edition

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5914]
Successful experiments with TCP-over-IPv8, QWebView, TiddlyWiki synchronization allows us to build a prototype of the Channels 3.0 system.

## The Goal
By adopting this architecture, we will bring all the wealth of Web technologies into Tribler. It will be like jumping directly from times of [Gopher](https://en.wikipedia.org/wiki/Gopher_(protocol)), FTP and FidoNet straight into Web 2.0 territory. 
:goat:  :arrow_right:  :rocket: 

![arc1](https://user-images.githubusercontent.com/2509103/104050394-dc94cf80-51e6-11eb-8cde-733fe0487895.jpg)

### TiddlyWiki

[TiddlyWiki](https://tiddlywiki.com/) is a one-of-a-kind wiki/application engine that **runs entirely in the browser**. Most important for us, TiddlyWiki is a **microcontent** system based on elements called **"tiddlers"**. In TiddlyWiki *everything* is a tiddler: content entries, pictures, plugins and even *the code itself*. Every system tiddler can be "shadowed" by a user-provided tiddler, akin to CSS system. This makes TiddlyWiki almost infinitely malleable, enabling [a vast library](https://dynalist.io/d/zUP-nIWu2FFoXH-oM7L7d9DM) of plugins, CSS styles, etc. (People even create [webshops](http://luckysushi.ru/habarovsk/heeg.html#Tempura) with it). Also, TiddlyWiki has a clear system for [backend synchronization](https://github.com/Jermolene/TiddlyWiki5/discussions/5269).

These two architectural features (backend-free and microcontent) make TiddlyWiki a perfect choice for Channels 3.0 **frontend**.

### TCP-over-IPv8
To enable sending tiddlers of arbitrary size, we have to employ some transport protocol over IPv8. To make stuff as simple as possible, I copied the code for a [pedagogical implementation](https://github.com/dound/vns/blob/master/TCPStack.py) of TCP in pure Python.
Initially, I hoped to use the `aioquic` package, but this proved to be an overkill. I preferred the TCP thing over @qstokkink 's uTP implementation, because:
 * TCP congestion control is more aggressive than uTP. This is important for real-time browsing remotely hosted channels.
 * TCP implementation is simpler and did not require extensive uTP messaging facilities (and porting from Twisted code)
 
The code is untested (except by manual test runs). I would like to push it to the main IPv8 repository **to enable native transparent sending of messages of arbitrary length through IPv8**. I would be glad if @qstokkink helps me with this :wink: 
UPDATE: done with EVA protocol

### QWebView

PyQt allows us to use QWebView widget to, basically, create a platform-independent, Chrome-based browser window inside our GUI. The networking stuff is handled by QT. In regards to XSS attacks, this will be perfectly safe for the user, because it will *not* use the user's native system browser, hence perfect isolation. **Each channel will be served by a separate instance of QWebView.**

### Libtorrent CDN
Common immutable data, such as the basic TiddlyWiki HTML page, common picture collections, etc, will be transported via torrents, the way we do in Channels 2.0. BitTorrent 2.0 torrent format assigns individual hashes to individual files. This feature allows us to use BitTorrent 2.0 as a CDN to search and host immutable common data. Mutable data will be replicated and gossiped directly with Channels 3.0.

### Channels 3.0 community
C3 community purpose is to host and serve **mutable** data (e.g. forums, wiki pages), as indicated in https://github.com/Tribler/tribler/discussions/5721 . Initially, it will not feature any collective editing. In fact, it will be served as a special sub-type of Channels 2.0 channel, using the same top-level navigation elements in the GUI.

### Persistence DB
C3 will [use PonyORM as the ORM of choice](https://github.com/Tribler/tribler/discussions/5865). Though the semantics will be different, and it will only use disk-based DB as a persistent cache. The idea of C3 is to **serve everything from memory**, but cache everything and dump the cache to disk periodically. This way, we completely avoid our DB-locking problem.

## The Roadmap

 - [x] Build C3 prototype able to synchronize data between TiddlyWikis
 - [ ] Embed C3 prototype into Tribler as an experimental feature (disabled by default), double-stack with Channels 2.0
 - [ ] Rework the default TiddlyWiki looks to simplify and make some default use cases (e.g. a blog, a list of torrents, etc)
 - [x] Enable real-time channel browsing in C3
 - [ ] Enable C3 as an alternative type of channel, double-stack with Channels 2.0
 - [ ] Implement an alternative frontend for Channels 2.0 in TiddlyWiki
 - [ ] Migrate Channels 2.0 GUI to TiddlyWiki representation (this will enable *styling* channels, etc.)
 - [ ] Implement Reddit-style comments in C3
 - [ ] Remove Channels 2.0 in favour of C3

Guys! This stuff will require *months* of work if I do it alone. Fortunately, the work can be split up very nicely into smaller architectural parts. So, if anyone volunteers to help me with this - I can always find a part that will be fun enough for you to make :wink:

**Comment by synctext** [comment]
Please always keep markdown in scope, as the whole web-stack brings in bloat.

**Comment by synctext** [comment]
### Browser technology is parasitic.

Browser technology is complex, lacks security awareness, and ignores privacy.  It is incompatible with the core value of Tribler.

11 years ago, the last industry leader who was pro-privacy described it like this: https://www.youtube.com/watch?v=39iKLwlUqBo
After our recent discussion, I'm now formulating it more clearly (and blunt). It extends our "**preservation of centrality**" rule. Any decentralised technology will degrade after a few years or decades to centralisation, usually at a higher level. Power and capital have a systemic tendency to become more [concentrated](https://www.aeaweb.org/articles?id=10.1257/aer.p20151060). Decentralised technology **MUST** be specifically designed with a defensive moat against re-centralisation. It happened to the distributed email protocol (GMail rule), Bitcoin (mining pool monopolies) and smart contracts (oracle nodes). It must be impossible-by-design for developers use a central server and take destructive shortcuts. Javascript-based technology, Chrome rendering, and hypertext in general are judged too toxic to use. Its too trivial to insert a single central gatekeeper server. As a university we are one of the last places which can be obsessive, principled, steadfast, compulsive, and idealistic. In the essential case of decentralisation we need to take the most academic pure position possible. Without 1 million users and without external developers this is mostly an internal cultural matter. Once the Tribler movement reaches escape velocity this becomes a cultural matter for our 100+ external developers. Resistance to centralisation is important for long-term enduring _critical societal infrastructure_.

The "no-browser policy" is the core of Tribler.

**Comment by ichorid** [comment]
>Javascript-based technology, Chrome rendering, and hypertext in general are judged too toxic to use.

Judged by whom?


It seems I'm lacking the imagination to see how using JS and HTML rendering of static HTML pages in a sandbox that is completely isolated from the Web (i.e. only allowed to query a limited subset of Tribler REST endpoints) can lead to centralization. Would you kindly provide a detailed scenario?

**Comment by devos50** [comment]
> It is incompatible with the core value of Tribler.

Depends on how you view it. As you also argued, browser technology, e.g., Chrome, is from a business perspective not compatible with an application such as Tribler that pushes for decentralization. This argument extends to packaging software such as Electron, that is using subsets of Google APIs. At the same time, I don't see many re-centralisation threats by using _web protocols_ such as HTML/CSS.

> Decentralised technology MUST be specifically designed with a defensive moat against re-centralisation.

I'm not sure how we can add technological safeguards to our software to defend against re-centralisation. Getting rid of the bootstrap servers is the first thing that comes to mind. The argument to use centralized components is usually convenience (e.g., as of yesterday, a part of my business infrastructure is using the free tier of Cloudflare to reduce the load on my servers and to speed up page requests). How we ensure convenience while still preventing re-centralisation?

**Comment by qstokkink** [comment]
> I don't see many re-centralisation threats by using web protocols such as HTML/CSS.

Agreed and to add to this: this even exists already. [ZeroNet](https://github.com/HelloZeroNet/ZeroNet) is doing this. In fact, relating this to our plugins suggestion of #6019, serving a core API of the P2P internals to Javascript ("plugin") developers also [already exists in ZeroNet](https://en.wikipedia.org/wiki/ZeroNet#Development_of_sites).

Whether or not this is a core value of Tribler and whether we should even want to compete with ZeroNet is another matter.

**Comment by synctext** [comment]
### Thinking Decentralised

Zeronet is a fascinating example, their site: "TLS encrypted connections", ".bit domain". When you do not alter the ecosystem, you may start re-using old mistakes like DNS and TLS. These are fundamentally central authority technologies. ```This is their way```.

Web people don't think decentralised. What I was trying to convey is something very "soft social science" like. The people from web-technologies may have good intentions and mature tools, but they miss something. This MIT professor writes it down very clearly: https://web.media.mit.edu/~mres/papers/decentralized-modeling.pdf Please browse this document for a bit, web people are never going to get good at thinking decentralised. These 24 pages by MIT explain great stuff like: "randomness plays an important role in creating order in many self-organizing systems". The whole web stack has centralised thinking and privacy leakage at the core. They are right, things **are** easier with central authorities, master servers, and full control. But users will never have power. Using web technology for decentralisation is an anti-pattern :fearful: _To force web people to think decentralised you need to take away everything they know_. Give them IPv8 and they understanding "this is different".

**Comment by ichorid** [comment]
> These 24 pages by MIT explain great stuff like

I've read all the 24 pages (except for the last 2 ofc), thoroughly. The author tells us about his experience of teaching children emergent behaviour in decentralized systems. It explicitly tells the story of how these children would always try to come up with centralized solutions _even in the programming language that was specifically designed for decentralization_. And how every time he had to hint the pupil of possibilities of decentralized systems...

It is entirely possible to use IPv8 in a centralized way (e.g. by creating one giant channel :wink: everyone is subscribed to). Conversely, it is equally possible to program decentralized stuff with the modern Web stack, see [WebTorrent](https://webtorrent.io/faq) for instance.

Indeed, some tools are better suited for some jobs. IPv8 community is a very nice reification of the concept of a uniform swarm of peers. As is HTML+JS is a very nice reification of the concept of an interactive, easy-to-modify GUI (which QT is not). And that is it! No one is going to put the "client-server" concept from the Web stack into Tribler. In other words, we're only going to use "local-only" parts of the Web stack, completely forbidding any form of remote connectivity or CDN (except for BitTorrent :wink:)

Think about it! Everything is centralized in this world! If we're going to do some decentralized stuff, we're going to do it from centralized stuff, because there is the only thing there is!

“**You have to make the good out of the bad because that is all you have got to make it out of.**” ― Robert Penn Warren, _All the King's Men_

**Comment by synctext** [comment]
We seem to reach different conclusions. Let me make it more colourful. Bittorrent is the only island of hope that humanity has for Internet freedom. We're growing this island and **never** connect it to the systemic corrupt mainland.

> Think about it! Everything is centralized in this world! If we're going to do some decentralized stuff, we're going to do it from centralized stuff, because there is the only thing there is!

Exactly, everything is centralised in this world (Bitcoin, Bittorrent and Tribler are really the only long-surviving exceptions). If we're going to do some decentralized stuff, we're going to have to take the harder path, because we are the only thing that is there. 

> No one is going to put the "client-server" concept from the Web stack into Tribler. 

Trust me on this one, it will be polluted. Master-slave thinking is deeply embedded into all Big Tech and web technology. That crowd will never take the harder path and always opt for convenience. Most of our master students [even do it](https://github.com/Tribler/trustchain-superapp/blob/master/musicdao/src/main/java/com/example/musicdao/wallet/WalletService.kt#L29).

**Comment by ichorid** [comment]
I understand your point now. It is just one step short of [Stallman's email-web daemon](https://stallman.org/stallman-computing.html). Our different backgrounds, personalities and socioeconomic positions push us towards preferring opposite strategies (though our goal remains the same). This leaves us with a single option of reaching consensus at the tactical level every time, which is elaborate, but workable.

Nonetheless, I got the last question for you: how are you planning to implement the GUI side of the plugins system _in a safe way_? (PyQT is completely unfit for that purpose. QT is a proprietary technology, there is no sandboxing in Python, etc.)

**Comment by synctext** [comment]
> I firmly refuse to install non-free software or tolerate its installed presence on my computer or on computers set up for me.

From that page... Yeah, its also about living pure!

**Comment by synctext** [comment]
### The JCenter Bintray disaster: death due to success
Another example of decentralised culture versus productivity. We relied for the Superapp on a central packaging website solution. A master student trained relentlessly in the art of decentralised system used this free service to complete his thesis mission. Now its terminated.

```Bintray has provided the open source community a free, universal cloud platform for publishing and distributing binaries.```
```We will have some short service brown-outs to remind users about the services that are going away on May 1st.```
![Screenshot from 2021-05-26 09-19-04](https://user-images.githubusercontent.com/325224/119618707-7ad6aa00-be03-11eb-9d2a-bb6ab80f4b20.png)
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
This has an impact on our science. We are expected to present a working Self-Sovereign Identity solution for all EU member states. Bintray has broken our Superapp. Impact on the SSI demo at our workshop, https://www.enisa.europa.eu/events/workshop-on-blockchain-based-digital-identity-solutions

**Comment by ichorid** [comment]
> ### The JCenter Bintray disaster: death due to success

Indeed, this is a fascinating example of how relying even on a single **centralised** service could break a **decentralised** system!

However, I still don't understand what this has to do with Channels 3.0 architecture and/or using **open-source** implementation of a HTML renderer to show **local** replicas of specifically-built HTML pages :shrug:
