### ISSUE TITLE
Blockchain Engineering - class of 2022 - Team Digital Euro III

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#6785]
**Project description:** Your task is to {partly} realise a new blockchain-based digital Euro. Delft university has obtained permission to [experiment with real digital Euros](https://www.delta.tudelft.nl/article/delft-cafe-premieres-eemcs-blockchain-euro) and live connection to the IBAN bank account system. You can build on this existing open source code. Reading: European Central Bank [report on digital Euro](https://www.ecb.europa.eu/pub/pdf/other/Report_on_a_digital_euro~4d7268b458.en.pdf), digital [Euro master thesis at Delft](https://repository.tudelft.nl/islandora/object/uuid%3A132faae8-6883-454f-a8ce-94735340dce9), the [progress report by China Central Bank](http://www.pbc.gov.cn/en/3688110/3688172/4157443/4293696/2021071614584691871.pdf) who is at least five years ahead of Europe. You are free to set your own target feature to focus on, for instance, high transaction rate, offline support, ease of use, etc.
[Cashless society report by NL central bank](https://www.dnb.nl/media/vqzngng5/2020_nr_2_toekomst_contant_geld_eng.pdf)

**Approach:** You will either extend our EuroToken implementation with new functionality, or improve existing functionality. The target feature(s) will be chosen depending on your expertise and interests. Suggestions/ideas are very much appreciated! Please make weekly updates of your progress on this ticket (e.g., with a screenshot). The expected deliverables are:
- A working end-to-end demo of your functionality.
- A __small__ readme.md writeup, describing your product, challenges, and design decisions.
- A merged and reviewed pull request to the [superapp repository](https://github.com/Tribler/trustchain-superapp).

**Possible project direction (subject to discussion next meeting):** Bitcoin-backed EuroTokens. Currently, EuroTokens are backed by Euro in the central bank network. Your project involves extending support for Bitcoin-backed EuroToken. You will have to modify the Bitcoin mining parameters, set up a private Bitcoin network, and mine some Bitcoin. These Bitcoins can be sent to a validator and exchanged for EuroToken. Give each user 10 EuroToken when joining the app.

Cardinal issues: preserve scalability, permissionless, primary function focus.

References:
- [EuroToken: An offline capable Central Bank Digital Currency](https://repository.tudelft.nl/islandora/object/uuid%3A132faae8-6883-454f-a8ce-94735340dce9?collection=education)
- [EuroToken implementation in the Superapp](https://github.com/Tribler/trustchain-superapp/tree/master/eurotoken/src/main/java/nl/tudelft/trustchain/eurotoken) 
- Various applications inside the superapp are using the EuroToken implementation. See for example the work by Joost on the [value transfer application](https://github.com/Tribler/trustchain-superapp/tree/master/valuetransfer/src/main/java/nl/tudelft/trustchain/valuetransfer). [Relevant issue](https://github.com/Tribler/tribler/issues/6029).

idea: tooling for enabling e-commerce. How can a webserver scan Trustchain? How can a server create Trustchain transaction? Where is the identity of the store stored? The phone is the webserver?? "shooting for the moon" task

ToDo:
- [X] Compile Superapp from the sources and run in emulator (record number of participants)
- [ ] Half of the group: investigate the fork of Bitcoin which operational is in [Luxury Communism](https://github.com/Tribler/trustchain-superapp/blob/master/currencyii/README.md) part of Superapp
- [ ] Half of group: investigate the digital Euro on Trustchain, part of the Superapp
- [ ] Milestone: each team member has 100 BTC on their phone (forked or real) call it "Euros" in the GUI

**Comment by synctext** [comment]
brainstorm
-assume 10k public iets with 0 to 100% double spending risk
-externalise the decision to transact to user
-offline risk focus
-focus on running code +X% design of this trust DB
-assume passport safe strong ID

**Comment by Nils134** [comment]
Proposed timeline and research questions

Planning:
3 weeks research
2 weeks to implement
2 weeks UX/UI

Research questions:
How to store and update the records of users, decentralized?
	Update between ratings
	Storage within phones
	
How to convey these risks to the user, intuitively?

Automatic block of users below a threshold? 

How to prevent fraud with updating records?

(How would we update these records, given transactions)?

Milestones:
Week 4:
	We set up a database (implementation)
	How to store and update? (research)
		Timestamp: Consensus
		Hash tree for information exchange / comparison
		Chunked update based on comparisons		
Week 6:
	We set up exchange mechanism (implementation)
	How to prevent fraud (research)
		Only update others
		Prevent circular updates
Week 8:
	Automatic block of users below a threshold 
	and convey risk (implementation)
	How to convey risk? (research)
		Color coding?
		Explanation?
		Double-spending?
Week 10:
	Do presentation
	Do readme

**Comment by synctext** [comment]
_Offline double spending focus_. Assumptions / constraints:
- assume there is a distributed ledger with all transactions
- pseudo-anonymous model, like Bitcoin, owner of wallets are unknown
- 
- out-of-scope: cal

**Comment by synctext** [comment]
- [ ] remove triple balance check
  - [ ] non-zero balance
  - [ ] validation at central server
  - [ ] non-validated money is blocked from spending

**Comment by synctext** [comment]
https://github.com/KoningR/stablecoin-exchange

**Comment by synctext** [comment]
- by default share the last 50 public keys you transacted with
  - only send, receive, or both?
  - Emergent effect: web-of-trust

**Comment by Fastjur** [comment]
Added a warning label to the send money fragment in eurotoken:
https://user-images.githubusercontent.com/1493561/160100362-a934b0d9-cda3-4f5e-b4ca-0b47b1f398d2.mp4

In the above video, it cycles through (by hot reloading so I don't have to rescan the code) the following situations:
- Sending to a public key with average trust score (30/70%)
- Sending to a public key with a low trust score (<30%)
- Sending to a public key with a good trust score (>70%)
- Sending to a public key without any trust score (warns the user that no info is available)

The trust score is now loaded from an asset that is included in the source files, a json file, but it shows the feature.

**Comment by synctext** [comment]
- currently the trust score is on a JSON file
- generate it on first-boot, store either in database or file
- no .APK to try yet, making solid progress.

**Comment by aimarinov** [comment]
#### Task division for the week:
1. Change the configuration file to include a boolean for demo mode 
2. Generate the keys and trustscores
3. Setup database to store the trustscores locally
4. Transmit the latest 50 transactions (Our id + 49 others)
5. Update upon the receiving (+ 1% for each one)
#### Goal: 
Demo - Showing the tasks as a whole unit

**Comment by Fastjur** [comment]
Added a simple toggle for demo mode, which will be used to generate 50 random (fake!) public keys if they are not enabled when there are no 50 transactions available. This is purely to demonstrate the working of sending the 50 public keys over the eva protocol.

![Screenshot_1648642933](https://user-images.githubusercontent.com/1493561/160833725-c42c85aa-d8a2-40c4-baea-6c3c6ec8f1b8.png)

**Comment by JoepdeJong** [comment]
The generator is implemented in https://github.com/pietertolsma/trustchain-superapp/pull/3. [Demo mode](https://github.com/pietertolsma/trustchain-superapp/blob/f645a0f336f228c31953881426ed5be2db37e18a/eurotoken/src/main/java/nl/tudelft/trustchain/eurotoken/community/EuroTokenCommunity.kt#L139) is now enabled by default

- [ ] Load demoModeEnabled from preferences.

@Fastjur can you look at this?

**Comment by pietertolsma** [comment]
https://user-images.githubusercontent.com/10885710/161044342-4adf8231-f07c-4ddd-b293-cd506f717865.mov

Demo of our working protocol for sending addresses to create a web of trust. Minor bug still with generating public keys in Demo mode, which @JoepdeJong will take care off!

**Comment by Fastjur** [comment]
> The generator is tested and implemented in [pietertolsma/trustchain-superapp#3](https://github.com/pietertolsma/trustchain-superapp/pull/3). [Demo mode](https://github.com/pietertolsma/trustchain-superapp/blob/f645a0f336f228c31953881426ed5be2db37e18a/eurotoken/src/main/java/nl/tudelft/trustchain/eurotoken/community/EuroTokenCommunity.kt#L139) is now enabled by default
> 
> * [ ]  Load demoModeEnabled from preferences.
> 
> @Fastjur can you look at this?

This has been fixed in our latest master branch at https://github.com/pietertolsma/trustchain-superapp

**Comment by pietertolsma** [comment]
https://user-images.githubusercontent.com/10885710/161045772-47690713-5e22-4132-898a-6352b6500255.mov

https://user-images.githubusercontent.com/10885710/161045815-e937b871-27cd-4645-b327-7c9dec6dd0b9.mov

Working demo. You can see how the sender transmits his 50 latest transaction addresses and how the trust score is updated. Note that currently demo mode is enabled, which generates 50 random keys. The random key generation is currently broken and is being fixed by @JoepdeJong , but other than that we are proud of what we achieved!

**Comment by pietertolsma** [comment]
https://user-images.githubusercontent.com/10885710/161062927-05458ef7-f769-427e-a60c-4dae396eaabb.mov

Working demo of our contribution! When DEMO is on, we generate 50 random keys with a seed.
- When the user scans the QR code of the receiving party, it transmits its latest 50 transaction counterparties. When DEMO mode is on, it generates 50 random keys based on a seed.
- Upon receiving the public key list, the user updates its trust score on every key received. Note how in the video, we receive the list twice from two transactions, so you see the trust score update from 0 to 1.

**Comment by synctext** [comment]
Discussed the ```radiating signs of frustration due to vagueness of assignment```. The process of clarifying the assignment during the running of the course, continuous large changes, and keep changing course of the project was frustrating. Agile!

**Comment by JoepdeJong** [comment]
TODO:

- [ ] Fix warning to show correct trust score (@Fastjur)
- [ ] Cleanup code
- [ ] Document/comment code
- [ ] Limit maximum score to 100% (@JoepdeJong)
- [ ] Write protocol specification (EPA protocol as binary) and readme
- [ ] Add readme to main readme using `read more`
- [ ] Make the PR

Remark:
- Be careful with updating ETH or BTC libs and dependencies.

**Comment by aimarinov** [comment]
@synctext Here is the [paper draft](https://github.com/Tribler/tribler/files/8396852/BE_research.pdf). It's formatted like a report instead of a paper, but that could be worked on.

**Comment by synctext** [comment]
Pull request with [docs](https://github.com/Tribler/trustchain-superapp/blob/d948a723d64bbb6e84e290139d2af7f63d173020/eurotoken/README.md).

**Comment by aimarinov** [comment]
[paper.pdf](https://github.com/Tribler/tribler/files/8450532/paper.pdf)

**Comment by aimarinov** [comment]
The newest version of the [paper](https://github.com/Tribler/tribler/files/8487766/Blockchain_paper.pdf).

**Comment by Fastjur** [comment]
### Pull request opened
https://github.com/Tribler/trustchain-superapp/pull/105

### Readme
https://github.com/pietertolsma/trustchain-superapp/blob/master/eurotoken/README.MD

### Debug APK
https://drive.google.com/file/d/1-qag_BBYBweuw9ENgHTe0t8p8RdR2nkX/view?usp=sharing

### Research paper
https://github.com/Tribler/tribler/files/8487766/Blockchain_paper.pdf

**Comment by synctext** [comment]
Euro readme intro:
EU member states of the Eurozone [are considering creating a blockchain-inspired digital Eurotoken using a P2P architecture](https://haldus.eestipank.ee/sites/default/files/2021-07/Work%20stream%203%20-%20A%20New%20Solution%20-%20Blockchain%20and%20eID_1.pdf). The superapp contains a fully functional digital cash implementation, still experimental and tested within 1 retail location for 1 morning in live production usage with real financial transactions.

**Comment by devos50** [comment]
This work has been completed, closing the issue 👍
