### ISSUE TITLE
Blockchain Engineering 2023 - Token Transaction Engine

### ISSUE THREAD

**Issue by InvictusRMC** [Tribler/tribler#7304]
Token transaction engine. Create a lightweight and fast token transaction engine for mobile devices. Your engine should be able to process 1000 transactions per second with standard 4G connectivity. Record these transactions within a simple SQLite backend. Realise simple primitives such as send/receive token primitives. Required background reading: [ConTrib: Universal and Decentralized Accounting in Shared-Resource Systems](https://dl.acm.org/doi/pdf/10.1145/3428662.3428789).

**Comment by InvictusRMC** [comment]
Progress:

All team member were able to compile from source 🎉, but please help AK!

**Comment by bbrockbernd** [comment]
Could you add sem as well: SDuveen

**Comment by nealsweijen61** [comment]
Created an IPv8 overlay

**Comment by nealsweijen61** [comment]
https://github.com/bbrockbernd/trustchain-superapp

**Comment by InvictusRMC** [comment]
* Team managed to get a community working

Next sprint:
  - Please update ticket before meeting
  - Get simple token structure up and running based on trustchain
  - Implement simple database structure

**Comment by AkramNexus** [comment]
Apk file for this week's sprint:

https://bit.ly/3ZITPTN

**Comment by nealsweijen61** [comment]
Contains possibilities to see message of others, send them tokens, and has a sqlite backend too! Also changed the project to a new android module

**Comment by bbrockbernd** [comment]
Meeting wednesday:

- Figure out what are the right conventions for refreshing peers, sending and receiving in a community. (Akram)
- Generate a lot of transactions, co routines (Sem)
- Grouping of transactions (Junbo)
- Fix UI bugs, and functionality (Bob)
- Lost messages (Neal)

**Comment by nealsweijen61** [comment]
Fixed UI bugs and functionality, written script for executing a lot of transaction(not tested) and created a way to resend messages when a message is not received.

**Comment by InvictusRMC** [comment]
Basic token structure working, good!

- Focus on using TrustChain ASAP: https://github.com/Tribler/kotlin-ipv8/blob/master/doc/TrustChainCommunity.md
- Please also have a look at already merged (!) code by other group: https://github.com/Tribler/trustchain-superapp/pull/136 
  - Extend if possible or ignore if not useful 😄 
- Working token structure using TrustChain: https://github.com/KoningR/eurotoken/blob/main/src/main/kotlin/Token.kt#L27

**Comment by nealsweijen61** [comment]
Implementation on trustchain, made dummy node(question about this), grouping of messages.

**Comment by InvictusRMC** [comment]
- Trustchain implementation is (almost) working ✔️ 
- Dummy nodes WIP
- Grouping of messages working ✔️
  - Please handle resends properly

**Comment by InvictusRMC** [comment]
Example README: https://github.com/Tribler/trustchain-superapp/blob/master/currencyii/README.md

**Comment by nealsweijen61** [comment]
Trustchain store for tokens(almost done), grouping and resending on trustchain, dummy nodes see app peers(but not the other way around??)

**Comment by InvictusRMC** [comment]
- Lesson learned: Kotlin and Python don't like talking with each other.

### TODO:
[ ] Readme
[ ] Running apk file
[ ] Write unit tests

# Prioritization
[ ] **Merge all code**
[ ] Focus on benchmarking
  - [ ] Flame graph
  - [ ] Networking benchmarks
  - [Example thesis with good analysis](https://github.com/Tribler/tribler/files/11136444/Performance_Analysis_of_an_Offline_Digital_Euro_Prototype.2.pdf)
[ ] Write Unit tests
[ ] Make PR and post APK to your issue
[ ] Readme
  - [ ] Add 1 section serving as documentation, look around for ideas:
      - https://github.com/Tribler/trustchain-superapp#peerchat
      - https://github.com/Tribler/trustchain-superapp#digital-euro
      - https://github.com/Tribler/trustchain-superapp#ai-trading-bot
      - https://github.com/Tribler/trustchain-superapp#luxury-socialism
      - https://github.com/Tribler/trustchain-superapp#freedom-of-computing-app-
  - [ ] Add animated GIF to your readme
  - [ ] Add flame graph and interesting statistics

**Comment by InvictusRMC** [comment]
Please also check with the missing team member whether they have any unavailable timeslots for the examination meeting on the 20th or 21st of April.

**Comment by AkramNexus** [comment]
New APK built from master branch on april 11th: https://we.tl/t-cjbelPP6z5

**Comment by nealsweijen61** [comment]
This sprint we finalized the trustchain implementation and now also use the grouping with this implementation. For benchmarking an enviroment a special enviroment has been created that only starts detoks engine and required other communites.
WIP: benchmark the newly implemented trustchain implementation.
