### ISSUE TITLE
Frozen Tests Registry

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7706]
This issue functions as a registry to keep track of detected frozen tests.

There's a possibility that the issue may not lie within a specific test but elsewhere. Hence, compiling a list of these tests could be beneficial, as it might reveal a pattern.

- [ ]  test_download_torrent_from_url: https://github.com/Tribler/tribler/actions/runs/6942446753/job/18885431246?pr=7705, #6606
- [x]  test_bilateral_transaction_timestamps: https://github.com/Tribler/tribler/actions/runs/6932482788/job/18856533640?pr=7703, #6854
- [ ] test_change_hops: https://github.com/Tribler/tribler/actions/runs/6535191519/job/17744992894?pr=7622#step:8:2797
- [ ] test_consolidate_channel_torrent: https://github.com/Tribler/tribler/actions/runs/5543081002/jobs/10118622017?pr=7542#step:6:1236
- [ ] test_commit_channel_torrent: https://github.com/Tribler/tribler/actions/runs/5543923045/jobs/10121257517?pr=7543#step:6:1272
- [ ] test_create_torrent_two_files: https://github.com/Tribler/tribler/actions/runs/5388219592/jobs/9780578427?pr=7507#step:6:942, #7508

**Comment by drew2a** [comment]
It seems that https://github.com/Tribler/tribler/pull/7708 actually fixed the frozen tests problem. 
I'll wait until next Monday and then close the issue (and all corresponding issues).
