### ISSUE TITLE
msc placeholder: something with passport-grade digital identity?

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#8062]
Exploring master thesis topic!

focus, bit of hands-on, not just paper stuff, connected to the real world.

**Comment by synctext** [comment]
### Architecting leaderless organisations

This thesis aims to invent a new method for large-scale human organisation, specifically leaderless socio-economic organisations with evolutionary capability. We will use the experimental economists methodology to explore the future of how our global economy may be organised, who will own it, and if taxes will be paid. Starting point is the automated online concept known as Decentralized Autonomous Organizations (DAO). We define a DAO as a leaderless organisation for organising any socio-economic activity. This emerging field holds the potential to provide the organisation principle for our upcoming AI-robot economy. We aim to explore primitive self-governance of DAOs, evolutionary principles, and economic activity under direct democratic control. This aims requires advancing the state-of-the-art in digital identity, programmable money, and Decentralised Autonomous Organisations (DAO). DAO science is still an emerging immature field with several open problems such as trusted infrastructure nodes, the founders with most decision making power, and rich-get-richer dynamics in general. The scientific problems to solve are inequality, democratic deficiency, design for evolution, and complex self-organisation. Prior technologies such such as smart contracts provide code execution at high cost without reliance on clouds or trusted third parties. However, a large "reality gap" remains with prior proposed architectures and realities of cybersecurity, complex self-organising systems, and self-evolving systems.
The state-of-the-art within digital identity is insufficient to support online voting at scale. This thesis builds upon prior work from Delft University, such as the root-of-trust for the upcoming passport-grade digital identity called EBSI/EDIC under eIDAS 2.0 legislation. Furthermore, we re-use the learnings from our programmable digital Euro trail with live connectivity to the IBAN banking system. Finally, the operational fully decentralised artist investment and music distribution platform will be re-used to minimize engineering effort of business logic. Central research questions are:
1) devise a digital identity architecture to enable DAO voting
2) devise voting principles for DAO governance and democratic control of programmable money
3) devise a security architecture for upgrades and self-evolution of a DAO

**Comment by synctext** [comment]
ToDo: find honor level master thesis topic
Honor track potential (some course grades still pending)
Thesis draft working title: "Realisation of online democracy: DAO e-voting using zero-knowledge constructs"

- [A secure end-to-end verifiable e-voting system using zero knowledge based blockchain](https://eprint.iacr.org/2018/466.pdf)
- [Non-interactive Zero-Knowledge Arguments for Voting](https://link.springer.com/chapter/10.1007/11496137_32)

**Comment by synctext** [comment]
ToDo: make a list of 3 With Honors msc projects. Could spend 3 months on this if Q4 is also available.
- Fighting misinformation using passport-grade trust
- On-device machine learning with collaborative networking
- Byzantine learning with strong identity

**Comment by Eragoneq** [comment]
Reviewed papers:

[Insight Into Voting in DAOs: Conceptual Analysis and a Proposal for Evaluation Framework](https://ieeexplore.ieee.org/abstract/document/10144510)
- General proposed framework for evaluation
	- SEED for Security, Efficiency, Effectiveness, Decentralization
- Since the consequences of security issues are serious, security should be the primary consideration when designing a DAO voting mechanism. A secure voting mechanism is the basis of the stability in DAOs. 
	- Good fundamentals for the cyber-sec based thesis
- Provides and evaluates some existing voting systems

[E-Voting With Blockchain: An E-Voting Protocol with Decentralisation and Voter Privacy](https://ieeexplore.ieee.org/abstract/document/8726645)
- General one of the first established blockchain based e-voting system
- Uses a Central Authority, thus it's not exactly applicable for DAO
- Promotes permissioned blockchain use
- Might be more applicable to general democratic elections

[DAO Decentralization: Voting-Bloc Entropy, Bribery, and Dark DAOs](https://arxiv.org/pdf/2311.03530)
- Introduced metric for decentralization
	- Could be connected more formally with the SEED framework and also uses some greek letters so overall interesting
	- Still theoretical as we cannot express users utility exactly, but could be used to analyze the security more in-depth
- Provides more examples of security issues related to decentralization
- Nice cited blog post: https://hackingdistributed.com/2018/07/02/on-chain-vote-buying/

[From Technology to Society: An Overview of Blockchain-Based DAO](https://ieeexplore-ieee-org.tudelft.idm.oclc.org/abstract/document/9403889)
- How blockchain technology may be used by the society
- Talks about problems when trying to incorporate DAOs
	- Consider irl usecases for the voting technology

[Blockchain for Electronic Voting System—Review and Open Research Challenges](https://www.mdpi.com/1424-8220/21/17/5874)
- Definitions of problems that need to be tackled by the voting systems
	- Detailed descriptions and a lot of properties
- As mentioned in future work, due to public nature of blockchain we cannot fulfill full privacy and secrecy, thus cannot be used in real elections
	- Finding a scheme that allows to mix the votes anonymously would be required

[A Liquid Democracy Enabled Blockchain-Based Electronic Voting System](https://onlinelibrary.wiley.com/doi/full/10.1155/2022/1383007)
- An example of an implementation of the blockchain electronic vote system
- Uses a permission Hyperledger Blockchain and centralized authorities
- Very basic, but provides a more engineering approach

[ElectionBlock: An Electronic Voting System using Blockchain and Fingerprint Authentication](https://ieeexplore.ieee.org/abstract/document/9425815)
- Another case study which implements an electronic vote system
- Also uses a newly-created permissioned blockchain for the election
- Provides a more detailed process for benchmarking and analysis of the prototype

[Internet voting in Estonia 2005–2019: Evidence from eleven elections](https://www-sciencedirect-com.tudelft.idm.oclc.org/science/article/pii/S0740624X2200051X)
- Analysis of the i-voting system implemented in Estonia
- Provides an in-depth look into the effects of electronic voting in the political aspect
	- Seems that since the implementation the trust stays within the same range, thus people don't get more comfortable with the system after longer time
	- The trust problem is being leveraged by the certain parties to dispute the election outcome
	- Legal framework is as important as technical one
- "Creating protocols that would provide better evidence for the i-voter while not enabling vote selling is currently an active area of research."
- i-voting is more convenient and more popular, but the trust and election turnout does not change

[E-Voting Meets Blockchain: A Survey](https://ieeexplore-ieee-org.tudelft.idm.oclc.org/abstract/document/10061373)
- Literature review of the existing systems that have been proposed and implemented by governments and private sector companies
	- Provides a lot of technological ideas and references to existing solutions

[Privacy-Preserving E-Voting System Supporting Score Voting Using Blockchain](https://www.mdpi.com/2076-3417/13/2/1096)
- A system using ZKP to create private elections
- Has a good performance results
- Seems like a good idea to implement and create a similar system, as it also has a nice strong theoretical fundamentals 

General thoughts:
- Votes have to be bound certain entity, different systems might use 1 token 1 vote, 1 person 1 vote etc. Depends on the requirements. Might be interesting to look into merit/expertise based voting, assign subject to the proposals and allow some votes to have higher weight. Connected with some identity framework and extendable properties
- Analyzing classical voting theory might be a good next step as well, finding a way to bridge the DAOs with the centralized elections and voting would be a great achievement. It would also be an important element in actually defining the "democracy" part of it, since there might be a reasoning in literature that explains some slight paradigm shifts or changes to the standard democratic process
- Often a problem with electronic systems and votes is with a trust. Even when we design a system that secures privacy of users and handles data in a proper way, the users might still not trust it due to lack of transparency. With real life ballots we can see that they are not marked and as such our vote cannot be distinguished, which is a lot harder to prove with electronic system. Analyzing the existing real life systems and the way the trust is distributed there might be interesting to note down.

**Comment by synctext** [comment]
- Awesome topic :tada: Worked on this in previous century :grin: 
- [Open Information Pools](https://www.usenix.org/legacy/publications/library/proceedings/usenix2000/freenix/full_papers/pouwelse/pouwelse_html/index.html) from 24 years ago: ```The democratic and reputation based policy can be combined into a system where votes of users are weighted with their reputation, and (dis)agreements influence the reputation of the submitter. A problem with the democratic policy is that users cannot always be objective and independant, for example the majority can determine that false popular belief is true.```
- All this physical meeting stuff is extremely naive. Impossibility result? [see the ancient stuff](https://web.archive.org/web/20181129111534/https://pgp.cs.uu.nl/doc/top_1000.html) High-barrier to participation.

**Comment by Eragoneq** [comment]
# Hmm 

- Iris detection seems unreliable with smartphone camera
    - Might still be better than some other biometrics
- Spoofing is still a huge problem, a photo could be used to impersonate someone
- Trusted hardware is required, and reliable check of the iris being actually "live"

# WorldCoin

Why is it bad?
- Trust is always an issue, how to verify any side-effects and tampering in real life?
    - How do traditional systems solve it, when it comes to government ID?

Main drawbacks:
- It creates a unique way to generate a key, but not to handle it. Users can later transfer the "real" personhood to another entity, thus act upon them
- Question of trust is based on the centrally created hardware to perform the scanning, the general design is open sourced, but there is no easy verification
- Proof of Personhood is not that useful on it's own, all the related credentials make it relevant in use
- How to address direct issues with the iris? 

[link](https://ieeexplore-ieee-org.tudelft.idm.oclc.org/abstract/document/10006664)

# EU

- EIDAS is still an interesting angle
    - Use NFC layer from the new IDs
    - Get all the data and create an entry in wallet app
    - PL ID also has photo in NFC chip, thus I can be used with face recognition for local storage
    - No easy/open-source access to the NFC chip data
    - Create hash for both and verify that face from ID and taken now match
        - Seems almost the same as the usual software KYC solutions
        - For now only the higher layer of private wallet differs
    - [EUDI Wallet framework](https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/blob/main/docs/arf.md)

# Grand Idea

- Multidimensional trust framework
- We cannot easily decide what trust/identity provider would we choose
- Each one has advantages and disadvanteges
- We can piggyback on top of all the ideas and create a single framework to allow for use of any
    - Gov ID / EUDI
    - Worldcoin
    - Real-life meetings
    - Biometric framework (?)
    - Reputation system
- Each of the providers would have certain properties, that could be voted on and updated based on the real capabilities
- Similar to cipher suite in TLS, we could choose Identity provider suite
    - Different identities would allow be given different levels of integrity etc.
    - Direct inclusion of ZKP would allow users to directly control, which data would be provided to the asking entities
        - A framework of questions that the sites could ask based on permission levels
        - eg. Do you have gov ID? What is the UID of your gov ID? Are you older than 18? Do you have <VC>? (Verifiable Credential)
        - Exact list of questions should be restricted, but extendable with some credentials
- A verification within the actual wallet could see whether the same ID has been used in multiple wallets
    - A system to disallow creating multiple wallets with the same kind of identity
    - This could in turn counter the issue of sybils in different systems
    - The problem becomes how can we verify the existance of the same ID in different wallets?
    - Synchronize/share the contents and check for their integrity without actually compormising on the privacy
- That would allow for easy integration of existing standards, while creating a new one that combines the ideas of the different ones
- Structure of the protocol/framework could be DAO/community based, which would allow for introduction of new providers based on the popular vote
- If integrated with some crypto network it could be made into a bounty system, where implementation of the given feature would have its bounty and then after the implementation the developer would receive the payout

**Comment by synctext** [comment]
still struggling to see a simple With Honors idea
- meta wallet is complex
- Sybil is complex

**Comment by Eragoneq** [comment]
# Voting in DAOs

## Sybils

- Verify users identity via EUDI wallet

## EUDI Wallet

- Use preexisiting issuers for the identity providers
- (?) Create own issuer with specific properties to hold within the wallet
    - Student card for usage in a university scale DAO

## Anonymity and Privacy, Confidentiality

- Have options for different levels of anonymity in the system
    - Allow for named voting (Only for selected people)
    - Completely anonymous voting
- Allow for users to change their vote (?)
    - Help with issue of selling votes

## Integrity

- Option to verify that the vote has been counted
    - No way to directly see what was the final vote on the given "ballot" (again avoid selling)
- Include multi-party computation to ensure that the vote is properly counted and cannot be changed by a malicious server
- Ensure some way to verify the integrity of the counting server
    - In a DAO context it would usually be done on the blockchain to check that

## Availability

- Ensure that system contains redundancy
- No single point of failiure

## Blockchain

- Use of Permissioned Blockchain (?)
    - Not a real DAO
- Gotta define the exact use case for this DAO/system
    - Most likely something EU related, due to the use of EUDI
    - Might be EU scale project, or smaller example one within EU country (university scale DAO)
        - Doing multiple countries would be a more aligned example with the EUDI usecase

## Works

[Unpacking DAOs](https://ieeexplore-ieee-org.tudelft.idm.oclc.org/abstract/document/10634404)
[Challenges of voting](https://www.mdpi.com/2073-8994/12/8/1328)

# Big Idea Again

> Privacy-Preserving E-Voting Through EUDI Wallet: A Zero-Knowledge Framework for Verifiable Democratic Participation

## Main assumptions
- Only specific people/organizations can start the voting process
    - Infrastructure may be controlled by the single entity
    - Cryptographic design must follow client side encryption
        - Ensures that even with controlled infra, no information is leaked
        - We cannot leak any identifiers, vote cannot be singled out when it has been mixed in
- We might used hybrid blockchain approach
    - Use only immutable and verifiable properties of blockchain
    - Traditional redundant centralized approach might help with scalability and security against DDOS attacks
- Similar architecture type to Estonia, but actually include the modern ideas of blockchain

**Comment by synctext** [comment]
- running code :astonished: :confetti_ball: 
- Great find that the EUID wallet is getting usable! 
- Related work
  - [Election verifiability in electronic voting protocols](https://link.springer.com/chapter/10.1007/978-3-642-15497-3_24)
  - Dream outcome for DAO voting ```Universal verifiability: anyone can check that the election outcome corresponds to the ballots published on the bulletin board.```
  - [Vote counting as mathematical proof](https://link.springer.com/chapter/10.1007/978-3-319-26350-2_41)
  - [Voting on Corda blog post](https://corda.net/blog/election-voting-on-corda/)
- Some incentive aligment and institutional design (like central bank gold storage for trust)
  - Restoring faith in society means restoring faith in democratic elections.
  - After digitisation, covid, misinformation and decades of social media subversion we need to take dramatic measures. If you break it, you become a billionaire. 😲 😨

**Comment by Eragoneq** [comment]
- Got the EUDI Verifier working locally
- Run the EUDI Issuer, but cannot fully test it because of self-signed certificates
- Started with the Thesis template and began filling in basic data and some related work papers

TODO:
- Modify the EUDI app to allow another cert issuers
- Possibly integrate functionality into superapp

**Comment by Eragoneq** [comment]
# Refs

[1](https://link-springer-com.tudelft.idm.oclc.org/chapter/10.1007/978-981-19-1607-6_50) [2](https://link-springer-com.tudelft.idm.oclc.org/chapter/10.1007/978-981-33-6835-4_17) [3](https://ieeexplore-ieee-org.tudelft.idm.oclc.org/abstract/document/9812616) [4](https://ieeexplore-ieee-org.tudelft.idm.oclc.org/abstract/document/10221917)

[5](https://www-sciencedirect-com.tudelft.idm.oclc.org/science/article/pii/S0306457321000947) - No research with real world experimentation (maybe focus on that as well)
[6](https://ieeexplore-ieee-org.tudelft.idm.oclc.org/abstract/document/9409949) - Nice info about Universal Verifiability Versus Coercion Resistance

## Theses
[6](https://ieeexplore-ieee-org.tudelft.idm.oclc.org/abstract/document/9314815) 
- Only for yes/no elections
- No resubmitting, no coercion resistance

[7](https://capuana.ifi.uzh.ch/publications/PDFs/21022_masterthesis.pdf)
- Master's Thesis extension to the Provotum suggested in [4]
- Provides very good fundamentals for this research

[8](https://capuana.ifi.uzh.ch/publications/PDFs/22765_BachelorThesis_RaphaelW%C3%A4spi.pdf) [9](https://capuana.ifi.uzh.ch/publications/PDFs/20916_master-arbeit-hofmann.pdf)

[](https://ieeexplore-ieee-org.tudelft.idm.oclc.org/abstract/document/9805556)
- MixNets

[Technical Specification of Swiss e-Voting v4.2 (2024)](https://eprint.iacr.org/2017/325.pdf)

[10](https://www.duo.uio.no/bitstream/handle/10852/95679/FINAL_boone_evan.pdf?sequence=5&isAllowed=y)
- Analysis of Estonia and Switzerland systems


# Design Challanges
- Secure Digital Identity Management - solved by using EUDI
- Anonymous Vote-Casting - needs strong crypto, ZKP
- Individualized Ballot Processes - resistance to phishing and vote-selling
- Ballot Casting Verifiability by the Voter - use of blockchain, pseudonymization
- Scalability, DDOS protection - cannot use too heavy processes
- Voter Trust - simplicity and availability of tools to verify

# Problems in current solutions
- Low throughput due to blockchains permissionless PoW - Use public permissioned blockchain (?)
- Identity Management is always an issue, gotta focus more on safely integrating the EUDI

# Ideas
- Use FIDO in conjuction with EUDI to achieve phishing resistant MFA
    - Others suggested SMS, but it should not be considered safe
    - Requries voters to own a FIDO key
- Allow fake votes to enable coertion resistance
    - Create option to cast a fake vote, that would be indistinguishable from the verifier perspective
    - Only voter and system would be able to see it
    - Voters could revote
    - System wouldn't count fake vote

# Code
- https://github.com/provotum

# What is needed next?
- Specific system requirements
  - Stakeholders
  - What properties are required?
  - Scalability
  - Trust assumptions

**Comment by synctext** [comment]
As systems people, please try to look at _real_ examples. Avoid fantasy digital designs, try 1979 real voting:
- [Voting Systems In Agricultural Cooperatives](https://ageconsearch.umn.edu/record/152898/files/fcrr2.pdf)
- [The one member-one vote rule in cooperatives](https://ageconsearch.umn.edu/record/46411/files/Volume%2015%20Article%204.pdf)


Decentralise election authority towards collective citizens
Register for citizens whom qualify to vote

**Comment by Eragoneq** [comment]
Not as much progress over the Christmas break, a lot of things to take care of thus, not able to code as much.

Start with the superapp to develop a MVP with the working connection between apps, shared identities and basic voting.
Focus on using the existing codebase from the EUDI and get to iterate of the design quickly.

Goal is to actually ship a working .apk

**Comment by Eragoneq** [comment]
Working on the code for the app.

Using the existing infrastructure of the Superapp to create a new app with integration of Trustchain.

<img src="https://github.com/user-attachments/assets/93eccd7e-bb84-4872-9845-1a1d1b1fdf59" width=250>
<img src="https://github.com/user-attachments/assets/c3838686-8440-4c84-89ee-8370eba1b9c9" width=250>
<img src="https://github.com/user-attachments/assets/2f109241-24c4-42a9-bad5-f82bdac6f906" width=250>

Elements not fully working yet, due to a lot of design choices that needed to be made and I didn't manage to make it fully working yet.

Contacted the EUDI team to help with the Verifier server to work with the real EUDI wallet to create tokens for identity to integrate them with the identity layer in the Superapp.

**Comment by synctext** [comment]
Solid tech progress! Designing the architecture, as you encounter design decisions while implementing everything all-at-once. Not an every expanding MvP approach. The _lets-get-coding_ development methodology 🤣 
No science angle yet! Some brainstorming for your to get the 'big words' and 'big claims' into thesis.Latex. 
- **Digital Democracy based on European passport-grade self-sovereign identity**. Put the voting part with zero-knowledge at the centre. Core element needs to be fancy security matters or scalability.
- **Robot company for the new industrial age**. Add local DeepSeek going inside superapp, add democratic-voting governance operational, and self-sovereign identity to prevent voting fraud. 
- **Cosmos-DAO: scalable capitalism using EU passport-grade security**. Its about rich-get-richer into cyberspace. New laws of economics, see: "[Robots and AI: A New Economic Era](https://www.econstor.eu/bitstream/10419/281298/1/Taylor-Francis_9781000626483.pdf)"
- **Decentralised Web economic architecture with democratic governance**. Save the world from Big Tech storyline. Have a decentralized platform with flow of money and ruled by the people, for the people.

**Comment by Eragoneq** [comment]
# Progress update

Current .apk: [link](https://drive.proton.me/urls/VHG98AHYVW#jFrkABdDCPa8)

## What has been done:

- Update the AGP of the whole superapp project
- Update dependencies
- Used modern Jetpack Compose API to create a basic Frontend for the app
- Configured and integrated (mostly) the EUDI Verifier via docker container
- Implemented basic vote sharing over IPv8 (still missing proper Trustchain integration)
- Managed to include `.so` files written directly in Rust as the native library code
  - Will be used to perform the ZKP crypto, as most libraries use Rust or C, not JVM languages

## Thesis contents

The main focus should be would be on the Digital Democracy. As I saw when also looking at the libraries, there is not much work done on local on-device voting and verification. Use of p2p technology with ZKP might allow to actually perform the voting in a real decentralized matter with strong anonymity and verification process. Definitely the architecture of the proofs, sharing, combining and scalability could be the core science angle of the whole project.

**Comment by synctext** [comment]
Scientific contribution brainstorm:
- Engineering is not science. 
- Switch for 2-3 sprints into **Science Mode**. Stop coding.
- Examples of scientific publications around 'provable secure'.
  - [The Provable Security of Ed25519: Theory and Practice](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9519456) ```We provide the first proof that Ed25519-IETF [7] is actually SUF-CMA secure. We prove that all Ed25519 schemes are resilient against key substitution attacks, and that if small subgroup keys are rejected as in LibSodium, a signature uniquely```
identifies a message, even for malicious keys.
  - [Provable Security Analysis of FIDO2](https://eprint.iacr.org/2020/756.pdf) - 39 page deep security analysis and proofs.
- Combination of secure, verifiable and voting protocols
  - [Alethea: A provably secure random sample voting protocol](https://ieeexplore.ieee.org/abstract/document/8429312/)
  - [Universal unconditional verifiability in e-voting without trusted parties](https://ieeexplore.ieee.org/abstract/document/9155182/)

**Comment by Eragoneq** [comment]
# Progress this sprint

[Master_Thesis_Draft_IEEE.pdf](https://github.com/user-attachments/files/19335902/Master_Thesis_Draft_IEEE.pdf)

**Comment by synctext** [comment]
### Making storyline clear with explicit novelty

For the past 20 years scientists have proposed digital democracy designs.
Consistently, these proposal lack two critical elements: legal infrastructure and a hardened root-of-trust.
The European Commission has proposed the required legal infrastructure for digital identity provided by commercial entities at passport-grade level of assurance. This EU regulatory framework ensures fraud, abuse, and cybercrime is punished.
Our Zero-knowledge proofs are not only grounded in technology, but also this EU legal framework.
Second, the root-of-trust for our work is directly linked to citizenship. The European Commission also has created a legal framework for identification and remote electronic authentication at passport-grade level. E-voting is only as strong as the weakest link, the root-of-trust for identity needs to be of a high level. This hardened root-of-trust infrastructure is used in our architecture in the form of an EUID wallet.

Add state-of-the-art

Present screenshots and detailed design

**Comment by Eragoneq** [comment]
# Progress during this sprint

Worked more on the content of the thesis. Changed the introduction to include the novelty quicker in the beginning and to explain what's important in that research. Created problem description with some of the requirements. Expanded the proposed framework. Created in-depth explanation of the protocol design. Started on some basic security analysis. Created preliminary evaluation based on the theoretical values proposed in the design. 

[Master_Thesis_Draft_v2_IEEE.pdf](https://github.com/user-attachments/files/19703748/Master_Thesis_Draft_v2_IEEE.pdf)

## Further research in the background

Looked a bit more into practical implementations of the system and what are currently the libraries which would allow for easier implementation of such system. Tried testing some stuff with the use of IPv8, but didn't spend too much time, to focus first on the theory.

**Comment by synctext** [comment]
Add a bit of a solid opening one-liner: we present the first realisation of e-voting targeting Internet scale with 8 billion people.

**Comment by Eragoneq** [comment]
# Progress during this sprint

Worked further on the thesis content. Reworked the existing sections to make them more concise. Focused more on the contributions, which would be that this is the *first smartphone-centric e-voting system and using EUDI wallet for the first time*. Moved the related work section later near the discussion to further compare our proposed framework to the solution proposed there and show how do we compare. 

General question remains: which sections should be expanded or removed?

[Master_Thesis_IEEE.pdf](https://github.com/user-attachments/files/20009695/Master_Thesis_IEEE.pdf)

## Code

I also looked a bit more into the actual code, but didn't focus yet on implementing the actual protocol, so this might be the plan for the next sprint, to get another version of the app running with the proof of concept implementing the actual protocol in some capacity.

## Feedback

E-voting is not going well, but slowely with proper technological improvement, we're seeing more opportunity to evolve the e-voting. "citizen centric" instead of smartphones, we focus on saying that it's *people* first, *people* are tallying the votes directly on their machines, so it's all truly democratic.

# Ideas for next sprint

- [ ] Work more in-depth on the code implementation of the protocol prototype.
  - [x] Integrate Trustchain messages
  - [ ] Create ZKP circuits and encryption mechanisms for the protocol
  - [x] Integrate the modified Verifier further to suit the needs of the protocol
  - [x] Update a few more UI screens to show some of the inner-workings 
- [ ] Update some of the selected section from the paper
  - [ ] Extend Background on comparison of traditional vs e-voting (?)
  - [ ] Include some general literature review references in Related Work (?)
  - [ ] Provide more direct comparison of our work with papers in Related Work section (?)
  - [ ] Add more implementation details information (based on the prototype)
- [x] Test the prototype on a 2-3 phones to check the connectivity and basic cryptographic assumptions

**Comment by synctext** [comment]
> first smartphone-centric e-voting system and using EUDI wallet for the first time.

This is making progress, but... The science should be even more explicit. 🤔 Smartphone is just compute, nothing to do with autonomy, architecture, integrity, and durability of democratic processes. Draft attempt for next storyline:

We present a complete re-imagination of e-voting. For decades e-voting made very little scientific progress. The current state-of-the-art still requires a wide range of intermediaries and trust in government-operated vote counting services. Given the decline of trust in society, a change of direction is required. We present the first design and the first operational implementation of a citizens-centric architecture. Our architecture is meticulously designed to remove all government servers, trusted services, or other intermediaries from democratic decision making.
We lowered the threshold for democratic participation by focusing on the most widely used digital devices used by billions of citizens: the smartphone. Our citizens-centric architecture is called SmartphoneDemocracy.

Our re-imagining of e-voting removes the government for all roles and shift them to self-sovereign citizens. Our SmartphoneDemocracy architecture gives anybody with a phone the power to organise elections, validate election integrity of elections, cast votes, and participate in democratic decision making in general. We redefine the state-of-the-art by moving all government election function to a decentralised web-of-trust formed by citizens. 

SmartphoneDemocracy is enabled by advanced technology such as self-sovereign identity, homomorphic encryption, non-interactive zero-knowledge proofs, and computational progress of smartphones. Our design, implementation, and performance analysis shows that a single smartphone is capable of checking millions of votes locally. Governments are not required for the core functions of democracy. Bitcoin showed it is possible to create money without governments or central banks. With SmartphoneDemocracy we reduce the problem of e-voting to registration of eligible voters. Voter registration remains a difficult issue. Traditionally voter registration requires a government agency. SmartphoneDemocracy enables anybody with a smartphone to organise a neighbourhood e-voting process. We show that voter registration is possible with merely a smartphone. This essentially removes the barriers of organising elections. The act of organising democratic processes no longer requires government permission. Our dream is that socio-economic changes and increased digital literacy will expose more of the global population with democratic decision making. In future work we aim to duplicate global movements such as Linux, Wikipedia, Bittorrent and Bitcoin. Our scientific contribution is making the choice for democracy itself democratic. We redefine democracy not as a system granted by institutions, but as a fundamental right—self-enforcing, self-validating, and accessible to anyone with a smartphone, anywhere in the world***.

***: _Last sentence is written by DeepSeek AI_

**Comment by Eragoneq** [comment]
# Code

Been working hard on the prototype. Had some troubles with designing the app architecture correctly to use the Trustchain. After getting some clarity from Rowdy it helped quite a bit to get things cleared up and create the working Trustchain layer. Most of the code is based on the already existing MusicDAO, which is architectured using all the modern components, which I was also using thus actually going in-depth into understanding it was the key part of development. 

## Functionality

All of the data is correctly stored in the local Trustchain database. All the shown data is based on the Trustchain blocks that are agreed upon by peers.

## Screenshots

<img src="https://github.com/user-attachments/assets/64439c91-f260-47e5-8b5b-feb1092c10a4" width=250>
<img src="https://github.com/user-attachments/assets/74e4dbb7-95d7-4881-b005-612aea67917f" width=250>
<img src="https://github.com/user-attachments/assets/a666f97e-a30d-4383-ae12-a93242f7553b" width=250>

## TODOs

- [x] Contact Harm to get a direct meeting, show the prototype and answer any questions required for Greenlight
- [ ] Add a README.md to explain the architecture and document the way it works for the future generations (like [this](https://github.com/Tribler/trustchain-superapp/blob/master/currencyii/README.md))
- [x] Further polish the UI actions and the backend code to properly test the required functionality
- [ ] Work on properly compiling the cryptographic library (using Rust cross-compilation for Android)

**Comment by Eragoneq** [comment]
This sprint mainly worked on the prototype and the preparation for the Thesis draft upload (at least 20 working days before).

[Pre-final Thesis Draft](https://github.com/user-attachments/files/20668549/Master_Thesis_IEEE.pdf)

With the prototype I worked mainly on cleaning up the backend and handling of the Blockchain blocks to insert them in the local database for use in the UI. Everything is being updated live and showing changes when they happen live. 
Updated the underlying Verifier and EUDI wallet app to use in the app and published my own [verifier](https://verifier.eragon.tech) to be used as the default verifier for the app.

## TODO
- [x] Check the formatting requirements for the Thesis (!)
- [ ] Add more information about the implementation and prototype, include photos
- [ ] Add conclusions and more discussion of the current approach.
- [x] Prepare notes for the presentation (!)

**Comment by synctext** [comment]
- Problem Description is list of system requirements, not science. Too obviously also, not informative: ```3. Privacy: Protecting voter privacy is paramount for free and fair elections```.
- No science or Problem Description: ```Secondarily, implementing the necessary cryptographic primitives (like Zero-Knowledge Proofs and Homomorphic Encryption) and managing data propagation in a peer-to-peer network directly on smartphones introduces potential performance overheads.```
- P2P and smartphone based represent the same underlying scientific principle: citizen power. 
- European Union Digital Identity (EUDI) Wallet is just a government-issued strong ID.
- Security&privacy are too obvious. More direct formulation: Our scientific aim is to completely remove the need to trust the government. The problem description is thus: how can we facilitate the democratic process using e-voting without relying on central infrastructure, without central institutions, and avoiding all third parties.
- Opening line Problem Description: **We focus on the problem of making democracy permissionless.**
- "Algorithm 1" ??
- Screenshot of running code?
- {_repeating_} Perhaps do 1 performance analysis graph. Focus on scalability with runtime of 1 million vote counting within smartphone.

**Comment by Eragoneq** [comment]
# Further Final Draft

[Master_Thesis_IEEE.pdf](https://github.com/user-attachments/files/20916590/Master_Thesis_IEEE.pdf)

**Comment by synctext** [comment]
```
The primary contributions of this research include developing
a first privacy-preserving e-voting protocol that leverages the
EUDI Wallet, as well as security analysis of the protocol.
```

Still missing 🤣  Promote the science! like...
We re-define the state-of-the-art in e-voting by establishing a new baseline for the amount for trust required for e-voting. Based on numerous designs proposed in the past and combining their ideas with modern zk-SNARK proof generation we remove trustest third parties, infrastructure required and eliminate the need for government permission to organise elections.

Bonus mission: .GIF of a few screens for future presentations and master classes.

**Comment by Eragoneq** [comment]
The Thesis is uploaded and available at: https://resolver.tudelft.nl/uuid:fa8fde99-009b-4539-a84c-55530bae6673
The final pdf file: [SmartphoneDemocracy.pdf](https://github.com/user-attachments/files/21019034/SmartphoneDemocracy.pdf)

Draft slides:  [slide_draft.pdf](https://github.com/user-attachments/files/21018926/slide_draft.pdf)

APK download: https://drive.proton.me/urls/TVCQ3EZNG8#cAW8J0TvBVdb

**Comment by synctext** [comment]
Thesis completed 🎉 

arXiv: [SmartphoneDemocracy: Privacy-Preserving E-Voting on Decentralized Infrastructure using Novel European Identity](https://arxiv.org/pdf/2507.09453)

_The digitization of democratic processes promises greater accessibility but presents challenges in terms of security, privacy, and verifiability. Existing electronic voting systems often rely on centralized architectures, creating single points of failure and forcing too much trust in authorities, which contradicts democratic principles. This research addresses the challenge of creating a secure, private e-voting system with minimized trust dependencies designed for the most versatile personal device: the smartphone. We introduce SmartphoneDemocracy, a novel e-voting protocol that combines three key technologies: the emerging European Digital Identity (EUDI) Wallet for Sybil-resistant identity verification, Zero-Knowledge Proofs for privacy-preserving validation, and a peer-to-peer blockchain (TrustChain) for a resilient, serverless public bulletin board. Our protocol enables voters to register and cast ballots anonymously and verifiably directly from their smartphones. We provide a detailed protocol design, a security analysis against a defined threat model, and a performance evaluation demonstrating that the computational and network overhead is feasible for medium- to large-scale elections. By developing and prototyping this system, we demonstrate a viable path to empower citizens with a trustworthy, accessible, and user-controlled digital voting experience._
